# **Converter format ".xlsx" en ".csv" et enregistrer dans repertoire "Output"**

In [1]:
import pandas as pd
import os

# Define the paths to the input files
comments_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Comments.xlsx"
posts_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Posts.xlsx"

# Define the output directory (working directory)
output_dir = "./"

# Read the Excel files
comments_df = pd.read_excel(comments_path)
posts_df = pd.read_excel(posts_path)

# Define the output file paths
comments_csv_path = os.path.join(output_dir, "Comments.csv")
posts_csv_path = os.path.join(output_dir, "Posts.csv")

# Save the DataFrames to CSV
comments_df.to_csv(comments_csv_path, index=False)
posts_df.to_csv(posts_csv_path, index=False)

print(f"Files have been saved to {output_dir}")

Files have been saved to ./

In [2]:
# Chemin de fichier CSV
posts_csv_path = "/kaggle/working/Posts.csv"

# Lire le fichier CSV dans de DataFrame
posts_df = pd.read_csv(posts_csv_path)

# Afficher les premières lignes pour vérifier
print("\nPosts DataFrame:")
posts_df

Posts DataFrame:

,ID,Contents,Lien Post,Nb Like,Nb Love,Nb Care,Nb Wow,Nb Sad,Nb Angry,Nb Haha,Company,Date
0,1,جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...,https://www.facebook.com/djezzy/posts/78822751...,272,45,0,1,1,76,14,Djezzy,2024-01-01
1,2,راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...,https://www.facebook.com/watch/?v=106882928102...,255,28,0,1,0,12,31,Djezzy,2024-01-04
2,3,It's Time To be a legend,https://www.facebook.com/djezzy/posts/39256499...,257,51,2,0,0,2,8,Djezzy,2024-01-10
3,4,Djezzy vous souhaite Yennayer amervuh! ⴰⵙⵙⴻⴳⴰ...,https://www.facebook.com/share/p/19UDNBoQ1k/,621,231,10,3,0,1,300,Djezzy,2024-01-11
4,5,قريباً ...,https://www.facebook.com/share/v/12B9LZySBRe/,288,49,4,0,0,3,24,Djezzy,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...
178,179,إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...,https://www.facebook.com/share/p/1KGHZQuXex/,208,46,6,0,0,0,1,Ooredoo,2024-03-26
179,180,مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...,https://www.facebook.com/share/v/1Bc7FtdDPx/,625,125,14,0,1,1,1,Ooredoo,2024-03-27
180,181,عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...,https://www.facebook.com/reel/954679512980806,280,40,7,1,1,0,0,Ooredoo,2024-03-28
181,182,ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...,https://www.facebook.com/watch/?v=193245186050...,148,35,3,0,0,2,0,Ooredoo,2024-03-28
182,183,أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...,https://www.facebook.com/OoredooDZ/posts/44139...,215,46,5,0,0,1,0,Ooredoo,2024-03-30

In [3]:
import pandas as pd

# Chemin de fichier CSV
comments_csv_path = "/kaggle/working/Comments.csv"

# Lire les fichiers CSV dans des DataFrames
comments_df = pd.read_csv(comments_csv_path)

# Afficher les premières lignes pour vérifier
print("Comments DataFrame:")
comments_df

Comments DataFrame:

,ID Post,User Name,Comments
0,1,Samir Bekhouche,NaN
1,1,Yanise Yanise,سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2,1,Jj Kie,كل عام و انتم بخير
3,1,Sakou Younes,كل عام وأنتم بخير
4,1,راني نعاني,كل عام وحنا بخير
...,...,...,...
4571,183,Ĺã Rõsë Ýb,❤️❤️
4572,183,نسمات هادئة,💕💕💕💕
4573,183,ملك ملهاش غيرك,❤❤❤❤❤❤🌹
4574,183,سعيدي رضا,NaN
4575,183,جيبلي فيت فيت,❤️❤️❤️❤️

In [4]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...
1      راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...
2                               It's Time To be a legend
3      Djezzy vous souhaite Yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...
179    مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

In [5]:
comments_df["Comments"]

0                                                     NaN
1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
                              ...
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4574                                                  NaN
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4576, dtype: object

# **Pretraitement**

## **Bibiliothèques**

In [6]:
import pandas as pd
import re
import emoji
import warnings

# **Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo"**

In [7]:
# Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo" (majuscule ou minuscule)
comments_df = comments_df[~comments_df["User Name"].str.lower().isin(["Djezzy", "Mobilis", "Ooredoo Algérie"])]

## **Suppression des valeurs NaN "Comments"**

In [8]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [9]:
def normalize_arabic(text):
    text = text.lower()
    text = re.sub("گ", "ك", text)
    text = re.sub("ڭ", "ك", text)
    text = re.sub("ڤ", "ق", text)
    text = re.sub("پ", "ب", text)
    text = re.sub("é", "e", text)
    text = re.sub("ê", "e", text)
    text = re.sub("ë", "e", text)
    text = re.sub("ç", "c", text)
    text = re.sub("à", "a", text)
    text = re.sub("â", "a", text)
    text = re.sub("ä", "a", text)
    text = re.sub("î", "i", text)
    text = re.sub("ï", "a", text)
    text = re.sub("æ", "ae", text)
    text = re.sub("œ", "oe", text)
    return text

# Appliquer la normalisation
comments_df["Comments"] = comments_df["Comments"].apply(normalize_arabic)
posts_df["Contents"] = posts_df["Contents"].apply(normalize_arabic)

In [10]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
5                                        كل عام وحنا بخير
                              ...
4570                                               🩷🩷🩷🩷🩷🩷
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4396, dtype: object

In [11]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#djezzy #happy_new...
1      راك en panne و خصك رصيد ؟\nمع خدمة tranquilo ت...
2                               it's time to be a legend
3      djezzy vous souhaite yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي ooredo...
179    مع ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

# **Nettoyage des données**

In [12]:
def clean_text(text):
    text = emoji.replace_emoji(text, replace='')  # Supprimer les emojis
    text = re.sub(r'http\S+ | htps\S+', '', str(text))  # Supprimer les hyperliens
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', str(text))  # Supprimer les URL
    text = re.sub(r'@\S+', '', str(text))  # Supprimer les mots commençant par @
    text = text.replace("_", " ").replace("#", "")  # Supprimer # et _
    text = text.replace("'", " ")  # Supprimer '
    text = re.sub(r'\. | , | ، | ؛', ' ', text)  # Remplacer certaines ponctuations
    text = re.sub(r'\bRT\b | \bRetweeted\b', '', text)  # Supprimer les mots réservés
    text = re.sub(r'[\u0660-\u0669\u06F0-\u06F9]+', '', text)  # Supprimer chiffres arabes
    
    # Supprimer les mots réservés
    reserved_words = r'\b(?:h{1,2}|m{1,2}|s{1,2}|Da|da|Euro|يورو|أورو|g|giga|Go|جيغا|جيجا|ساعة|دج|دينار(?: جزائري)?|Dollars?|دولار)\b'
    text = re.sub(reserved_words, '', text, flags=re.IGNORECASE)
    
    if isinstance(text, str):  # Vérifier si c'est bien une chaîne de caractères
        # Supprimer tout caractère spécial sauf l'alphabet arabe et latin
        text = re.sub(r'[^a-zA-Z0-9\u0600-\u06FF\s]', '', text)
        
        # Supprimer les voyelles courtes arabes (حركات)
        harakat = "[\u064B-\u0652]"  # Comprend ً ٌ ٍ َ ُ ِ ّ ْ
        text = re.sub(harakat, '', text)

    text = re.sub(r"(.)\1{2,}", r"\1", text)  # Supprimer les caractères consécutifs en double
    text = re.sub('\d+', ' ', text)  # Supprimer les chiffres
    text = text.replace('\n', ' ').replace('/', ' ')  # Supprimer sauts de ligne et /
    text = re.sub(r'[^\w\s]', '', text)  # Supprimer les caractères spéciaux

    return text.strip()

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

# Remplacer les valeurs nulles par une chaîne vide
comments_df["Comments"] = comments_df["Comments"].fillna('')
posts_df["Contents"] = posts_df["Contents"].fillna('')

comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [13]:
posts_df["Contents"]

0         جازي تتمنى لكم سنة سعيدة djezzy happy new year
1      راك en panne و خصك رصيد  مع خدمة tranquilo تاع...
2                                it  time to be a legend
3      djezzy vous souhaite yennayer amervuh     جازي...
4                                                  قريبا
                             ...
178    إثارة الألعاب تتعاش مع الأحباب خاصة كي ooredoo...
179    مع ooredoo ديما رابحين  وجدنا لكم حاجة جديدة ب...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية حملوا التطبيق شاه...
Name: Contents, Length: 183, dtype: object

In [14]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة  فليكسيت    و بدأت...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
5                                        كل عام وحنا بخير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    شكون تغلقلو نيمروه و راح لاجونس قدر يسترجعو جا...
4567    walah cnx ta koum rahi t ayi lyamat hadou safi...
4569    سلام عليكم اوريدو عندي مشكل كل مرة نفليكسي تنح...
Name: Comments, Length: 3993, dtype: object

# **Stemming**

#### La méthode stemming est le processus de suppression d'une partie d'un mot ou de réduction d'un mot à sa racine pour avoir des données utiles pour l’analyse des sentiments. Il supporte principalement le stemming léger (en supprimant les préfixes et les suffixes) et donne toutes les segmentations possibles. Il utilise un automate à états finis modifié qui permet de générer toutes les segmentations

In [15]:
!pip install farasa langdetect
!pip install git+https://github.com/MagedSaeed/farasapy.git

Collecting farasa
  Downloading Farasa-0.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect) (1.17.0)
Downloading Farasa-0.0.1-py2.py3-none-any.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 80.4 MB/s eta 0:00:00
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=e15c75a87d415ce13048a210e1c5ac317bc650f595fd6340c4ea250064d2b4fa
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect
Installing collected packages: langdetect, farasa
Successfully installed farasa-0.0.1 langdetect-1.0.9
Collecting git+https://github.com/MagedSaeed/farasapy.git
  Cloning https://github.com/MagedSaeed/farasapy.git to /tmp/pip-req-build-yhnv57aq
  Running command git clone --filter=blob:none --quiet https://github.com/MagedSaeed/farasapy.git /tmp/pip-req-build-yhnv57aq
  Resolved https://github.com/MagedSaeed/farasapy.git to commit 9200fb78f9e4d102a4b63b54b9b0ace84ff9d43e
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from farasapy==0.0.14) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from farasapy==0.0.14) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (2025.1.31)
Building wheels for collected packages: farasapy
  Building wheel for farasapy (setup.py) ... done
  Created wheel for farasapy: filename=farasapy-0.0.14-py3-none-any.whl size=12919 sha256=d009d11a74118c46eb27a6d1ac2abe925aa162c99dad0f7c8122697a90cf9168
  Stored in directory: /tmp/pip-ephem-wheel-cache-aqgx6cg0/wheels/ae/56/72/2ba224ca1aa5d0822d5b1ea26be589d58732b74a6dd2a04f62
Successfully built farasapy
Installing collected packages: farasapy
Successfully installed farasapy-0.0.14

In [16]:
from farasa.stemmer import FarasaStemmer
from nltk.stem.snowball import SnowballStemmer
from langdetect import detect

# Initialisation des stemmers
farasa_stemmer = FarasaStemmer("arabic")

# Détection et stemming en fonction de la langue
def stem_text(text):
    try:
        if isinstance(text, str):  # Vérifier si c'est bien du texte
            text = farasa_stemmer.stem(text)
        return text
    except:
        return text  # Retourner tel quel en cas d'erreur

# Appliquer le stemming aux colonnes concernées
comments_df["Comments"] = comments_df["Comments"].apply(stem_text)
posts_df["Contents"] = posts_df["Contents"].apply(stem_text)

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'farasa-api.qcri.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

100%|██████████| 241M/241M [06:40<00:00, 602kiB/s]

[2025-02-19 16:31:35,928 - farasapy_logger - WARNING]: Be careful with large lines as they may break on interactive mode. You may switch to Standalone mode for such cases.

In [17]:
posts_df["Contents"]

0              جاز تمنى ل سنة سعيد djezzy happy new year
1      راك en panne و خص رصيد مع خدمة tranquilo تاع d...
2                                 it time to be a legend
3      djezzy vous souhaite yennayer amervuh جاز تقدم...
4                                                   قريب
                             ...
178    إثارة لعب تتعاش مع حبيب خاص كي ooredoo تضاعف إ...
179    مع ooredoo ديما رابح وجد ل حاجة جديد باش ربح أ...
180    عاش مع بعض جو رمضاني رائع من خلال إفطار mega f...
181    ضاعف اشتراك إنترنت خاص ب خلال شهر رمضان على my...
182    أنتم من عاشق سينما عربي حمل تطبيق شاهد استمتع ...
Name: Contents, Length: 183, dtype: object

In [18]:
comments_df["Comments"]

1       سلام على رحمة لدى مشكلة فليكسيت و بدأ نقص شوي ...
2                                       كل عام و أنتم خير
3                                         كل عام أنتم خير
4                                          كل عام حنا خير
5                                          كل عام حنا خير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    شك تغلقلو نيمروه و راح لاجونس قدر يسترجعو جاوب...
4567    walah cnx ta koum rahi t ayi lyamat hadou safi...
4569    سلام على اوريدو عند مشكل كل مرة نفليكسي تنحولي...
Name: Comments, Length: 3993, dtype: object

# **Stop word**

Les Stop words ou bien les mots vides sont les mots couramment utilisés qui sont généralement ignorés par le moteur de recherche, tels que the, اللذين, إن, etc. Ces mots sont supprimés pour économiser de l’espace dans la base de données et le temps de traitement, c’est pour cette raison qu’on va essayer dans l’étape suivante d’utiliser le package ntlk pour supprimer ces mots vides.

Le package stop-words est utilisé pour supprimer les mots vides du texte en Python. Ce paquet contient des mots vides dans de nombreuses langues comme l’anglais, l’Arabe, le français, l’espagnol et plus encore.

In [19]:
# import necessary libraries
import nltk
from nltk.corpus import stopwords

# Charger les stopwords pour l'arabe et le français
nltk.download('stopwords')
arabic_stopwords = set(stopwords.words('arabic'))
french_stopwords = set(stopwords.words('french'))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [20]:
# Affiche quelques mots (stop-words)
print(stopwords.words('arabic'))

['إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّ']

In [21]:
# Affiche quelques mots (stop-words)
print(stopwords.words('french'))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']

In [22]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in arabic_stopwords and word not in french_stopwords]
    return " ".join(filtered_words)

# Appliquer la suppression des stop-words
comments_df["Comments"] = comments_df["Comments"].apply(remove_stopwords)
posts_df["Contents"] = posts_df["Contents"].apply(remove_stopwords)

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

In [23]:
posts_df["Contents"]

0                جاز تمنى سنة سعيد djezzy happy new year
1      راك panne خص رصيد خدمة tranquilo تاع djezzy كل...
2                                 it time to be a legend
3      djezzy souhaite yennayer amervuh جاز تقدم أحر ...
4                                                   قريب
                             ...
178    إثارة لعب تتعاش خاص ooredoo تضاعف إنترنت my oo...
179         ooredoo ديما رابح حاجة جديد باش ربح أستناونا
180    عاش جو رمضاني رائع خلال إفطار mega ftour دارتو...
181    ضاعف اشتراك إنترنت خاص خلال شهر رمضان my oored...
182    عاشق سينما عربي حمل تطبيق شاهد استمتع أفضل فيل...
Name: Contents, Length: 183, dtype: object

In [24]:
comments_df["Comments"]

1       سلام رحمة مشكلة فليكسيت بدأ نقص شوي شويا  لزون...
2                                                 عام خير
3                                                 عام خير
4                                             عام حنا خير
5                                             عام حنا خير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    شك تغلقلو نيمروه لاجونس قدر يسترجعو جاوبوني رب...
4567    walah cnx koum rahi ayi lyamat hadou safi jour...
4569     سلام اوريدو مشكل مرة نفليكسي تنحولي خمسلاف وش حل
Name: Comments, Length: 3993, dtype: object

## **Correction des abréviations & Regroupement phonétique**

In [25]:
abbreviations = {
    "cnx": "connexion",
    "mrc": "merci",
    "num": "numéro"
    # Ajoutez d'autres abréviations ici
}

def replace_abbreviations(text):
    words = text.split()
    return ' '.join([abbreviations[word] if word in abbreviations else word for word in words])

comments_df['Comments'] = comments_df['Comments'].apply(replace_abbreviations)
posts_df['Contents'] = posts_df['Contents'].apply(replace_abbreviations)

## **Sauvegarde des fichiers nettoyés**

In [26]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

# Sauvegarder les fichiers après la translittération
comments_df.to_csv("Comments_clean.csv", index=False)
posts_df.to_csv("Posts_clean.csv", index=False)

print("Prétraitement terminé et fichiers enregistrés !")

Prétraitement terminé et fichiers enregistrés !