# **Converter format ".xlsx" en ".csv" et enregistrer dans repertoire "Output"**

In [1]:
import pandas as pd
import os

# Define the paths to the input files
comments_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Comments.xlsx"
posts_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Posts.xlsx"

# Define the output directory (working directory)
output_dir = "./"

# Read the Excel files
comments_df = pd.read_excel(comments_path)
posts_df = pd.read_excel(posts_path)

# Define the output file paths
comments_csv_path = os.path.join(output_dir, "Comments.csv")
posts_csv_path = os.path.join(output_dir, "Posts.csv")

# Save the DataFrames to CSV
comments_df.to_csv(comments_csv_path, index=False)
posts_df.to_csv(posts_csv_path, index=False)

print(f"Files have been saved to {output_dir}")

Files have been saved to ./

In [2]:
# Chemin de fichier CSV
posts_csv_path = "/kaggle/working/Posts.csv"

# Lire le fichier CSV dans de DataFrame
posts_df = pd.read_csv(posts_csv_path)

# Afficher les premières lignes pour vérifier
print("\nPosts DataFrame:")
posts_df

Posts DataFrame:

,ID,Contents,Lien Post,Nb Like,Nb Love,Nb Care,Nb Wow,Nb Sad,Nb Angry,Nb Haha,Company,Date
0,1,جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...,https://www.facebook.com/djezzy/posts/78822751...,272,45,0,1,1,76,14,Djezzy,2024-01-01
1,2,راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...,https://www.facebook.com/watch/?v=106882928102...,255,28,0,1,0,12,31,Djezzy,2024-01-04
2,3,It's Time To be a legend,https://www.facebook.com/djezzy/posts/39256499...,257,51,2,0,0,2,8,Djezzy,2024-01-10
3,4,Djezzy vous souhaite Yennayer amervuh! ⴰⵙⵙⴻⴳⴰ...,https://www.facebook.com/share/p/19UDNBoQ1k/,621,231,10,3,0,1,300,Djezzy,2024-01-11
4,5,قريباً ...,https://www.facebook.com/share/v/12B9LZySBRe/,288,49,4,0,0,3,24,Djezzy,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...
178,179,إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...,https://www.facebook.com/share/p/1KGHZQuXex/,208,46,6,0,0,0,1,Ooredoo,2024-03-26
179,180,مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...,https://www.facebook.com/share/v/1Bc7FtdDPx/,625,125,14,0,1,1,1,Ooredoo,2024-03-27
180,181,عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...,https://www.facebook.com/reel/954679512980806,280,40,7,1,1,0,0,Ooredoo,2024-03-28
181,182,ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...,https://www.facebook.com/watch/?v=193245186050...,148,35,3,0,0,2,0,Ooredoo,2024-03-28
182,183,أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...,https://www.facebook.com/OoredooDZ/posts/44139...,215,46,5,0,0,1,0,Ooredoo,2024-03-30

In [3]:
import pandas as pd

# Chemin de fichier CSV
comments_csv_path = "/kaggle/working/Comments.csv"

# Lire les fichiers CSV dans des DataFrames
comments_df = pd.read_csv(comments_csv_path)

# Afficher les premières lignes pour vérifier
print("Comments DataFrame:")
comments_df

Comments DataFrame:

,ID Post,User Name,Comments
0,1,Samir Bekhouche,NaN
1,1,Yanise Yanise,سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2,1,Jj Kie,كل عام و انتم بخير
3,1,Sakou Younes,كل عام وأنتم بخير
4,1,راني نعاني,كل عام وحنا بخير
...,...,...,...
4571,183,Ĺã Rõsë Ýb,❤️❤️
4572,183,نسمات هادئة,💕💕💕💕
4573,183,ملك ملهاش غيرك,❤❤❤❤❤❤🌹
4574,183,سعيدي رضا,NaN
4575,183,جيبلي فيت فيت,❤️❤️❤️❤️

In [4]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...
1      راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...
2                               It's Time To be a legend
3      Djezzy vous souhaite Yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...
179    مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

In [5]:
comments_df["Comments"]

0                                                     NaN
1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
                              ...
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4574                                                  NaN
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4576, dtype: object

# **Pretraitement**

## **Bibiliothèques**

In [6]:
import pandas as pd
import re
import emoji
import warnings

# **Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo"**

In [7]:
# Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo"
comments_df = comments_df[~comments_df["User Name"].isin(["Djezzy", "Mobilis", "Ooredoo Algérie"])]

## **Suppression des valeurs NaN "Comments"**

In [8]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [9]:
def normalize_arabic(text):
    text = text.lower()
    text = re.sub("گ", "ك", text)
    text = re.sub("ڭ", "ك", text)
    text = re.sub("ڤ", "ق", text)
    text = re.sub("پ", "ب", text)
    text = re.sub("é", "e", text)
    text = re.sub("ê", "e", text)
    text = re.sub("ë", "e", text)
    text = re.sub("ç", "c", text)
    text = re.sub("à", "a", text)
    text = re.sub("â", "a", text)
    text = re.sub("ä", "a", text)
    text = re.sub("î", "i", text)
    text = re.sub("ï", "a", text)
    text = re.sub("æ", "ae", text)
    text = re.sub("œ", "oe", text)
    return text

# Appliquer la normalisation
comments_df["Comments"] = comments_df["Comments"].apply(normalize_arabic)
posts_df["Contents"] = posts_df["Contents"].apply(normalize_arabic)

In [10]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
5                                        كل عام وحنا بخير
                              ...
4570                                               🩷🩷🩷🩷🩷🩷
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4371, dtype: object

In [11]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#djezzy #happy_new...
1      راك en panne و خصك رصيد ؟\nمع خدمة tranquilo ت...
2                               it's time to be a legend
3      djezzy vous souhaite yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي ooredo...
179    مع ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

# **Nettoyage des données**

In [12]:
def clean_text(text):
    text = emoji.replace_emoji(text, replace='')  # Supprimer les emojis
    text = re.sub(r'http\S+ | htps\S+', '', str(text))  # Supprimer les hyperliens
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', str(text))  # Supprimer les URL
    text = re.sub(r'@\S+', '', str(text))  # Supprimer les mots commençant par @
    text = text.replace("_", " ").replace("#", "")  # Supprimer # et _
    text = text.replace("'", " ")  # Supprimer '
    text = re.sub(r'\. | , | ، | ؛', ' ', text)  # Remplacer certaines ponctuations
    
    # Supprimer les mots réservés
    text = re.sub(r'\bRT\b | \bRetweeted\b', '', text)
    reserved_words = r'\b(?:h{1,2}|m{1,2}|s{1,2}|Da|da|DA|Euro|يورو|أورو|g|جيقا|km|kilometre|m|mb|gb|حي|giga|milles|esim|Mo|mo|ko|mega|Go|جيغا|جيجا|ساعة|دج|دينار(?: جزائري)?|Dollars?|دولار)\b'
    text = re.sub(reserved_words, '', text, flags=re.IGNORECASE)
    
    text = re.sub(r'[\u0660-\u0669\u06F0-\u06F9]+', '', text)  # Supprimer chiffres arabes
    
    # Supprimer tout caractère spécial sauf l'alphabet arabe et latin
    text = re.sub(r'[^a-zA-Z0-9\u0600-\u06FF\s]', '', text)
        
    # Supprimer les voyelles courtes arabes (حركات)
    harakat = "[\u064B-\u0652]"  # Comprend ً ٌ ٍ َ ُ ِ ّ ْ
    text = re.sub(harakat, '', text)

    text = re.sub(r"(.)\1{2,}", r"\1", text)  # Supprimer les caractères consécutifs en double
    text = re.sub('\d+', ' ', text)  # Supprimer les chiffres
    text = text.replace('\n', ' ').replace('/', ' ')  # Supprimer sauts de ligne et /
    text = re.sub(r'[^\w\s]', '', text)  # Supprimer les caractères spéciaux

    return text.strip()

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

# Remplacer les valeurs nulles par une chaîne vide
comments_df["Comments"] = comments_df["Comments"].fillna('')
posts_df["Contents"] = posts_df["Contents"].fillna('')

comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [13]:
posts_df["Contents"]

0         جازي تتمنى لكم سنة سعيدة djezzy happy new year
1      راك en panne و خصك رصيد  مع خدمة tranquilo تاع...
2                                it  time to be a legend
3      djezzy vous souhaite yennayer amervuh     جازي...
4                                                  قريبا
                             ...
178    إثارة الألعاب تتعاش مع الأحباب خاصة كي ooredoo...
179    مع ooredoo ديما رابحين  وجدنا لكم حاجة جديدة ب...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية حملوا التطبيق شاه...
Name: Contents, Length: 183, dtype: object

In [14]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة  فليكسيت    و بدأت...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
5                                        كل عام وحنا بخير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    شكون تغلقلو نيمروه و راح لاجونس قدر يسترجعو جا...
4567    walah cnx ta koum rahi t ayi lyamat hadou safi...
4569    سلام عليكم اوريدو عندي مشكل كل مرة نفليكسي تنح...
Name: Comments, Length: 3968, dtype: object

# **Stemming**

#### La méthode stemming est le processus de suppression d'une partie d'un mot ou de réduction d'un mot à sa racine pour avoir des données utiles pour l’analyse des sentiments. Il supporte principalement le stemming léger (en supprimant les préfixes et les suffixes) et donne toutes les segmentations possibles. Il utilise un automate à états finis modifié qui permet de générer toutes les segmentations

In [15]:
!pip install farasa langdetect
!pip install git+https://github.com/MagedSaeed/farasapy.git

Collecting farasa
  Downloading Farasa-0.0.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 13.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect) (1.17.0)
Downloading Farasa-0.0.1-py2.py3-none-any.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 91.8 MB/s eta 0:00:00
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=09106b31cd7623d35e1ffe21603a099ded6514ab5f7c32383c9659ad2a8038c6
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
Successfully built langdetect
Installing collected packages: langdetect, farasa
Successfully installed farasa-0.0.1 langdetect-1.0.9
Collecting git+https://github.com/MagedSaeed/farasapy.git
  Cloning https://github.com/MagedSaeed/farasapy.git to /tmp/pip-req-build-ltf6pavz
  Running command git clone --filter=blob:none --quiet https://github.com/MagedSaeed/farasapy.git /tmp/pip-req-build-ltf6pavz
  Resolved https://github.com/MagedSaeed/farasapy.git to commit 9200fb78f9e4d102a4b63b54b9b0ace84ff9d43e
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from farasapy==0.0.14) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from farasapy==0.0.14) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->farasapy==0.0.14) (2025.1.31)
Building wheels for collected packages: farasapy
  Building wheel for farasapy (setup.py) ... done
  Created wheel for farasapy: filename=farasapy-0.0.14-py3-none-any.whl size=12919 sha256=9c8483545b2759e1c86c7426ccfd27bde5166c5a6092ad2425326dc88f56cab3
  Stored in directory: /tmp/pip-ephem-wheel-cache-5np2a0ho/wheels/ae/56/72/2ba224ca1aa5d0822d5b1ea26be589d58732b74a6dd2a04f62
Successfully built farasapy
Installing collected packages: farasapy
Successfully installed farasapy-0.0.14

In [16]:
from farasa.stemmer import FarasaStemmer
from nltk.stem.snowball import SnowballStemmer
from langdetect import detect

# Initialisation des stemmers
farasa_stemmer = FarasaStemmer("arabic")

# Détection et stemming en fonction de la langue
def stem_text(text):
    try:
        if isinstance(text, str):  # Vérifier si c'est bien du texte
            text = farasa_stemmer.stem(text)
        return text
    except:
        return text  # Retourner tel quel en cas d'erreur

# Appliquer le stemming aux colonnes concernées
comments_df["Comments"] = comments_df["Comments"].apply(stem_text)
posts_df["Contents"] = posts_df["Contents"].apply(stem_text)

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'farasa-api.qcri.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

100%|██████████| 241M/241M [07:09<00:00, 562kiB/s]

[2025-02-20 06:19:30,870 - farasapy_logger - WARNING]: Be careful with large lines as they may break on interactive mode. You may switch to Standalone mode for such cases.

In [17]:
posts_df["Contents"]

0              جاز تمنى ل سنة سعيد djezzy happy new year
1      راك en panne و خص رصيد مع خدمة tranquilo تاع d...
2                                 it time to be a legend
3      djezzy vous souhaite yennayer amervuh جاز تقدم...
4                                                   قريب
                             ...
178    إثارة لعب تتعاش مع حبيب خاص كي ooredoo تضاعف إ...
179    مع ooredoo ديما رابح وجد ل حاجة جديد باش ربح أ...
180    عاش مع بعض جو رمضاني رائع من خلال إفطار ftour ...
181    ضاعف اشتراك إنترنت خاص ب خلال شهر رمضان على my...
182    أنتم من عاشق سينما عربي حمل تطبيق شاهد استمتع ...
Name: Contents, Length: 183, dtype: object

In [18]:
comments_df["Comments"]

1       سلام على رحمة لدى مشكلة فليكسيت و بدأ نقص شوي ...
2                                       كل عام و أنتم خير
3                                         كل عام أنتم خير
4                                          كل عام حنا خير
5                                          كل عام حنا خير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    شك تغلقلو نيمروه و راح لاجونس قدر يسترجعو جاوب...
4567    walah cnx ta koum rahi t ayi lyamat hadou safi...
4569    سلام على اوريدو عند مشكل كل مرة نفليكسي تنحولي...
Name: Comments, Length: 3968, dtype: object

## **Correction des abréviations & Regroupement phonétique**

In [19]:
abbreviations = {
    "mrc": "merci",
    "num": "numéro",
    "numro": "numéro",
    "nn": "non",
    "شوي": "قليل",
    "شويا": "قليل",
    "لزونيتي": "الوحدات",
    "حنا": "نحن",
    "علا": "على",
    "أسإلتي": "أسئلة",
    "حاص": "خاص",
    "مدام": "بينما",
    "رن": "نحن",
    "رانا": "نحن",
    "بون": "حسن",
    "ان": "سنة",
    "توس": "جميع",
    "سبيسيال": "منفرد",
    "سبيال": "منفرد",
    "باه": "لكي",
    "زاف": "كثيرا",
    "بزاف": "كثيرا",
    "نتمني": "نتمنى",
    "فظلكم": "فضلكم",
    "ضلم": "ظلم",
    "ردى": "رد",
    "علاش": "لماذا",
    "علاه": "لماذا",
    "علا": "لماذا",
    "هذ": "هذه",
    "تبرعو": "تبرع",
    "ابليكاسيو": "تطبيق",
    "أبليكاسيون": "تطبيق",
    "أبليكاسيو": "تطبيق",
    "الخاص بكم": "نتاعكم",
    "ديرولنا": "افعلو لنا",
    "ديرو": "افعلو",
    "نحا": "نزع",
    "دير": "افعل",
    "حاجة": "شيء",
    "نتع": "خاص ب",
    "تاع": "خاص ب",
    "تع": "خاص ب",
    "جاوبوني": "رد علي",
    "ران": "أنا",
    "مشتاركه": "مشاركة",
    "رحو": "فرح",
    "هدي": "هدية",
    "يروح": "يذهب",
    "يجي": "يأتي",
    "وقتاه": "متى",
    "وقتاش": "متى",
    "وقتش": "متى",
    "تردولنا": "ترجعون",
    "نتاع": "خاص ب",
    "شك": "من",
    "نحيتوها": "نزع",
    "نحيتو": "نزع",
    "نحيت": "نزع",
    "سلفلي": "قرض",
    "سلفولي": "قرض",
    "غدوة": "غدا",
    "تلقى": "تجد",
    "نأكتيفيها": "تفعيل",
    "ناكتيفي": "تفعيل",
    "نعانيو": "نعانون",
    "ميت حال": "رديء",
    "مفهمتش": "لم أفهم",
    "انو": "انه",
    "علاب": "لهذا",
    "ليتو": "أصبحتم",
    "تدو": "تأخذون",
    "الى": "إلى",
    "خاستني": "أحتاج",
    "خستني": "أحتاج",
    "مشى": "تعمل",
    "شكا": "شكوى",
    "زرو": "سيء",
    "زيرو": "سيء",
    "سرفيك": "خدمة",
    "سرفيس": "خدمة",
    "جيزي اب": "djezzy app",
    "nchlh": "incha allah",
    "riglou": "regler",
    "bah": "pour",
    "nwaliw": "devenir",
    "k": "comme",
    "مراح": "لا",
    "مهمش": "لا",
    "تعليع": "تعليق",
    "زااف": "كثيرا",
    "khayan": "سرق",
    "djezzyy": "djezzy",
    "ومرديتش": "لم ترد",
    "واش": "ماذا",
    "منبعد": "بعد ذلك",
    "تفتحش": "لا تفتح",
    "أدار": "أفعل",
    "راه": "أصبح",
    "لازم": "يجب",
    "pix": "pixx",
    "Twanty": "Twenty",
    "orod": "prod",
    "imtiyaaz": "imtiyaz",
    "tm": "ok",
    "نم": "تم",
    "جداو": "جدا",
    "زلب": "زبل",
    "كونطرا": "عقد",
    "شري": "شراء",
    "توب": "رائع",
    "جزل": "جزيلا",
    "ياسر": "كثير",
    "golde": "gold",
    "mknch": "introuvable",
    "rani": "je suis",
    "شكرالكم": "شكرا لكم",
    "viv": "vive",
    "عتل": "أرسل",
    "لاجونس": "مقر",
    "rpnd": "repond",
    "prv": "prive",
    "svp": "s il vous plais",
    "yennayer": "سنة",
    "amervuh": "سعيدة",
    "en": "في",
    "panne": "عطل",
    "happy": "سعيدة",
    "koum": "votre",
    "ayi": "faible",
    "new": "جديدة",
    "year": "سنة",
    "years": "سنة",
    "شنو": "ما هو",
    "هدا": "هذا",
    "شالنج": "تحدي",
    "li": "qui",
    "bghi": "aime",
    "ndirlo": "faire",
    "yji": "viens",
    "lah": "pourquoi", 
    "raho": "que il",
    "hbs": "arret",
    "بر": "فقط",
    "غي": "إلا",
    "حسنو": "اصلاح",
    "سقمو": "اصلاح",
    "جوند": "legend",
    "يجاند": "legend",
    "غي": "إلا",
    "ارطيا": "جزء",
    "علجال": "من أجل",
    "تثقال": "بطء",
    "كون": "ليت",
    "بغى": "أراد",
    "تفرج": "مشاهدة",
    "ماتش": "مباراة",
    "رجا": "رجاء",
    "متمشلكش": "لا تعمل",
    "لايص": "أماكن",
    "حب": "أريد",
    "نسقسي": "أسأل",
    "اذ": "إذا",
    "يمتي": "بلا حدود",
    "خسني": "أريد",
    "باطل": "مجانا",
    "قولد": "gold",
    "تعيف": "بطء",
    "غادي": "س",
    "نسييو": "محاولة",
    "نلعبو": "لعب",
    "نكونو": "أكون",
    "عب": "لعب",
    "كف": "كيف",
    "اللهيوفقناجميعاقولويارب": "الله يوفقنا جميع اقولو يارب",
    "congratulations": "مبروك",
    "berkaw": "arret",
    "ser": "vole",
    "تردوش": "لا تردون",
    "هضرت": "كلام",
    "باش": "لكي",
    "تحلى": "حل",
    "لينا": "لنا",
    "حض": "حظ",
    "wech": "Quoi",
    "ndirou": "faire",
    "bach": "pour",
    "nrebhou": "gagner",
    "elfe": "mille",
    "mabrok": "felicitations",
    "li": "a",
    "koules": "tous",
    "moucharikones": "participants",
    "el": "les",
    "mabrouk": "مبروك",
    "اطوههالي": "اعطوها لي",
    "شاب": "جميل",
    "يعطيكمالصحة": "يعطيكم الصحة",
    "illa": "lent",
    "th": " ",
    "ta": " ",
    "na": " ",
    "a": " ",
    "sui": " ",
    "woww": "wow",
    "يارب": "يا رب",
    "كلشي": "كل شيء",
    "كنكتي": "تواصل",
    "مانكونيكتيش": "لا أتواصل",
    "شما": "هل يوجد",
    "يووز": "yooz",
    "يوز": "yooz",
    "وش": "ما هو",
    "وشمن": "أي",
    "ديما": "dima",
    "راه": "يوجد",
    "معجبتنيش": "سيء",
    "تحبسلي": "توقف",
    "انتاع": "ل",
    "ال": " ",
    "لوس": "plus",
    "شكراوريدو": "شكرا أوريدو",
    "در": "فعل",
    "رهي": "هناك",
    "كاين": "يوجد",
    "مباغش": "لا يريد",
    "يمدلي": "يعطيني",
    "يخرجو": "خروج",
    "اكتر": "أكثر",
    "مايمشيش": "لا يعمل",
    "سوايع": "ساعة",
    "محبتش": "لا",
    "جام": "مستحيل",
    "تمشلي": "تعمل",
    "ريفي": "خاص",
    "قاع": "كل",
    "منربحش": "لا أربح",
    "منربحوش": "لا أربح",
    "نقارع": "صبر",
    "مفتحتوهاليش": "لا تفتح",
    "ابونمون": "اشتراك",
    "مساج": "رسالة",
    "رجعو": "رد",
    "صحيتو": "شكرا",
    "لاتوجد": "لا توجد",
    "نلقاش": "لا أجد",
    "كريدي": "رصيد",
    "ريبونديولنا": "رد",
    "جد": "جدا",
    "ينحيولي": "نزع",
    "يحذفولي": "نزع",
    "عمر": "أبدا",
    "ماسلفت": "قرض",
    "مدايرا": "لم أفعل",
    "راهي": "إنها",
    "فور": "ممتاز",
    "هايل": "ممتاز",
    "مليح": "جيد",
    "شابة": "جميل",
    "ماصلحتليش": "لا تعمل",
    "إستلاف": "قرض",
    "خص": "أريد",
    "هاذ": "هذا",
    "شحال": "كم",
    "تاكتيفيه": "تفعيل",
    "حتان": "كي",
    "كيفاش": "كيف",
    "غلطة": "خطأ",
    "ختاريت": "خيار",
    "ديالي": "خاص بي",
    "حاب": "أريد",
    "ويل": "أو",
    "ابعث": "ارسال",
    "goold": "gold",
    "ماتجاوبوش": "عدم رد",
    "مهدى": "هدية",
    "واشهرالجاي": "شهر موالي",
    "نخلصش": "لا أدفع",
    "ابليس": "plus",
    "تأكتيفها": "تفعيل",
    "هيل": "hayla",
    "هاذي": "هذه",
    "وشمن": "ما هي",
    "جزاير": "جزائر",
    "معن": "معنى",
    "معن": "معنى",
    "فاه": "فيها",
    "فاش": "كيف",
    "بر": "فقط",
    "مكوبي": "مقطوع",
    "مي": "لكن",
    "مايمشيلك": "لا يعمل",
    "نديرلهم": "عمل",
    "تتمسخرو": "استهزاء",
    "ريبونديو": "رد",
    "plais" : "من فظلكم",
    "كفاه": "كيف",
    "ندموندي": "طلب",
    "دخلتو": "دخل",
    "العالميه": "عالمية",
    "قات": "بقي",
    "nechlh": "incha allah",
    "jdida": "جديد",
    "كيفما": "كفماه",
    "أفعل": "اندير",
    "ذيم": "دائما",
    "وين": "أين",
    "راهي": "هي",
    "ماندمت": "ندم",
    "حشو": "خدعة",
    "انشاءاللهتكونمننصيبي": "ان شاء الله تكون من نصيبي",
    "نتمنالهم": "أتمنى",
    "حشو": "خدعة",
    "راحوش": "لم",
    "بادن": "باذن",
    "الي": "الذي",
    "تغلقلو": "غلق",
    "نيمروه": "رقم",
    "يسترجعو": "استرجاع",
    "رانيني": "ranini",
    "عقوبة": "عاقبة",
    "قوب": "عاقبة",
    "غاش": "لا يريد",
    "حطو": "وضع",
    "لينا": "لنا",
    "ستمرار": "مستمر",
    "لابيلكاسيو": "تطبيق",
    "لبليكاسيو": "تطبيق",
    "متمشيش": "لا تعمل",
    "حبستوها": "توقف",
    "حمال": "تحميل",
    "مزان": "ميزان",
    "جيه": "جهة",
    "فلعاصمة": "عاصمة",
    "nztjwice": " ",
    "refvf": " ",
    "b": " ",
    "br": " ",
    "ابار": "يبارك",
    "يحفضكم": "يحفظكم",
    "يلوس": "plus",
    "تاه": "متى",
    "بف": " ",
    "sagmou": "regler",
    "شويش": "switch",
    "بغية": "أريد",
    "dialkom": "vous",
    "sahel": "facile",
    "toop": "top",
    "هنيء": "مبروك",
    "puse": "sim",
    "pui": "puis",
    "nerbah": "gagne",
    "ghir": "sauf",
    "بيان": "جيدا",
    "نحافضو": "حفاظ",
    "تخلاص": "انتهاء",
    "متعرفش": "لا تعلم",
    "خاصتا": "خاصة",
    "وفى": "و في",
    "خاصتا": "خاصة",
    "ظل": "دائما",
    "مدرتو": "لم تفعل",
    "لموبليس": "موبيليس",
    "را": "إنه",
    "صر": "حدث",
    "rah": "il est",
    "gae": "tous",
    "dok": "maintenant",
    "لابليكاسيون": "تطبيق",
    "كلش": "كل",
    "مشاءالله": "ما شاء الله",
    "حبس": "توقف",
    "زيد": "أيضا",
    "ميقراسيون": "تبديل",
    "نجاوب": "أجيب",
    "راحت": "ذهب",
    "متسواش": "سيء",
    "متسواش": "سيء",
    "تعكم": "خاص بكم",
    "حقاهايلة": "ممتاز",
    "حمدلله": "حمد لله",
    "رحمن": "رحمان",
    "نشال": "شاء الله",
    "ماشاء": "ما شاء",
    "تنحولي": "نزع",
    "خمسلاف": "خمسة ألف",
    "جزى": "جزاك",
    "نشاء": "إن شاء",
    "إنشاءالله": "ان شاء الله",
    "نشالله": "ان شاء الله",
    "شاءالله": "شاء الله"
}

def replace_abbreviations(text):
    words = text.split()
    return ' '.join([abbreviations[word] if word in abbreviations else word for word in words])

comments_df['Comments'] = comments_df['Comments'].apply(replace_abbreviations)
posts_df['Contents'] = posts_df['Contents'].apply(replace_abbreviations)

In [20]:
from collections import defaultdict
import re

# Dictionnaire de regroupement phonétique
phonetic_groups = {
    "تعبئة": ["كنفليكسيو", "نفليكسي", "نفليكسيو", "فليكس",  "نفلبكسى", "فليكسيت", "كسي", "فليكسي"],
    "connexion": ["conx", "cnx", "ncx", "conexion", "connection"],
    "reseau": ["wrizo", "rizo", "riso", "rysou", "resou", "risou"],
    "اصلاح": ["ريقلوه", "ريقلو", "صلحو", "ريقولو", "صلحونا", "عدلو", "رقليو", "تريغليونا", "لوتصلحولينا", "تريقلونا", "وريقليو"],
    "شبكة": ["ريزو", "اريزو", "خط", "خطي", "رزو"],
    "ما به": ["واشي", "وشبيه", "شبيه"],
    "لا يوجد": ["ماكاش", "مكانش", "مكاش", "والو", "معنديش", "الو"],
    "أي": ["كش", "كاش"],
    "إنترنت": ["كونيكسيون", "كونكسيو", "كونكزيون", "كونيكسيو", "ليدوني", "انترنت", "انترنيت","نترنت", "أنترنات", "أنترنت","نت", "كنكسيو", "كونيكسو", "انترن"],
    "جازي": ["جايز", "جاز", "دجيزي", "دجزي", "جيزي", "جايزي"],
    "أسقاس": ["اسوكاس", "اصكاس", "اسقاس", "اسيقاس", "اسكاس"],
    "أمقاز": ["أموقاز", "امكاز", "امقاز"],
    "رمز": ["كود", "رزم"],
    "بارك": ["بارى", "بيار", "باراك", "يبارك"],
    "شريحة": ["لابيس", "لبيس", "بيس", "لابوس", "لبييس", "لبووس", "pis"],
    "أوريدو": ["اريدوو", "اوريدو", "لأوريد", "ياؤريدوا", "اوريدوا", "واوريدو", "ااوريدو", "اريدو"],
    "ان شاء": ["إنشاء", "نشالله", "انشاء"],
    "ilimite": ["ilm", "ilmt", "ilimiti", "ilim"],
}

# Création d’un mapping inverse (pour accélérer la recherche)
phonetic_mapping = {}
for standard, variations in phonetic_groups.items():
    for variant in variations:
        phonetic_mapping[variant] = standard

# Fonction de remplacement des variantes phonétiques
def replace_phonetic_variants(text):
    words = text.split()
    return ' '.join([phonetic_mapping[word] if word in phonetic_mapping else word for word in words])

comments_df['Comments'] = comments_df['Comments'].apply(replace_phonetic_variants)
posts_df['Contents'] = posts_df['Contents'].apply(replace_phonetic_variants)

In [21]:
posts_df["Contents"]

0            جازي تمنى ل سنة سعيد djezzy سعيدة جديدة سنة
1      راك في عطل و أريد رصيد مع خدمة tranquilo خاص ب...
2                                   it time to be legend
3      djezzy vous souhaite سنة سعيدة جازي تقدم ل أحر...
4                                                   قريب
                             ...
178    إثارة لعب تتعاش مع حبيب خاص كي ooredoo تضاعف إ...
179    مع ooredoo dima رابح وجد ل شيء جديد لكي ربح أس...
180    عاش مع بعض جو رمضاني رائع من خلال إفطار ftour ...
181    ضاعف اشتراك إنترنت خاص ب خلال شهر رمضان على my...
182    أنتم من عاشق سينما عربي حمل تطبيق شاهد استمتع ...
Name: Contents, Length: 183, dtype: object

In [22]:
comments_df["Comments"]

1       سلام على رحمة لدى مشكلة تعبئة و بدأ نقص قليل ق...
2                                       كل عام و أنتم خير
3                                         كل عام أنتم خير
4                                          كل عام نحن خير
5                                          كل عام نحن خير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563    من غلق رقم و راح مقر قدر استرجاع رد علي من رب ...
4567    walah connexion votre rahi t faible lyamat had...
4569    سلام على أوريدو عند مشكل كل مرة تعبئة نزع خمسة...
Name: Comments, Length: 3968, dtype: object

# **Stop word**

Les Stop words ou bien les mots vides sont les mots couramment utilisés qui sont généralement ignorés par le moteur de recherche, tels que the, اللذين, إن, etc. Ces mots sont supprimés pour économiser de l’espace dans la base de données et le temps de traitement, c’est pour cette raison qu’on va essayer dans l’étape suivante d’utiliser le package ntlk pour supprimer ces mots vides.

Le package stop-words est utilisé pour supprimer les mots vides du texte en Python. Ce paquet contient des mots vides dans de nombreuses langues comme l’anglais, l’Arabe, le français, l’espagnol et plus encore.

In [23]:
# import necessary libraries
import nltk
from nltk.corpus import stopwords

# Charger les stopwords pour l'arabe et le français
nltk.download('stopwords')
arabic_stopwords = set(stopwords.words('arabic'))
french_stopwords = set(stopwords.words('french'))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [24]:
# Affiche quelques mots (stop-words)
print(stopwords.words('arabic'))

['إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّ']

In [25]:
# Liste des mots à exclure
words_to_remove = [
    'لا', 'كثيرا', 'كثير', 'دون', 'ليس', 'ليست', 'فلا', 'غير', 'لسنا', 'لكن', 'لاسيما', 
    'لست', 'لستم', 'لم', 'لن', 'ليست', 'ليسوا', 'بئس', 'نعم', 'ساء', 'عجبا', 'عيانا', 
    'غالبا', 'فضلا', 'حسبنا', 'حسب', 'أجل', 'أما', 'إما', 'بس', 'بلى', 
    'بينما', 'حاشا', 'حبذا', 'دون', 'عدا', 'عسى', 'غير', 'فلا', 'كلا', 
    'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 
    'لعل', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لن', 'لو', 'لولا', 'لوما', 'لئن', 
    'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 
    'هيت', 'هيهات', 'وإذ', 'ولا', 'ولكن', 'ولو'
]

# Filtrer les stop words pour exclure les mots dans `words_to_remove`
final_arabic_stopwords = [word for word in arabic_stopwords if word not in words_to_remove]

# Afficher la liste finale
print(final_arabic_stopwords)

['لمّا', 'سبحان', 'أمسى', 'لكم', 'تسعون', 'سبع', 'غ', 'أيلول', 'إنَّ', 'وَيْ', 'إلَيْكَ', 'هاتي', 'ذين', 'أغسطس', 'خمسمائة', 'سوف', 'كي', 'بي', 'ذه', 'لعلَّ', 'أبريل', 'غين', 'كرب', 'خلف', 'ارتدّ', 'أينما', 'هناك', 'ف', 'في', 'الألى', 'ست', 'وا', 'وما', 'إلا', 'جنيه', 'هنالك', 'يناير', 'طاق', 'تاء', 'ثمان', 'جير', 'درى', 'ك', 'إذما', 'مهما', 'قبل', 'هبّ', 'ر', 'كيف', 'هذه', 'هيا', 'كل', 'تانِك', 'واهاً', 'جلل', 'كيفما', 'جوان', 'ما أفعله', 'باء', 'أقبل', 'دواليك', 'حمٌ', 'قاطبة', 'أعلم', 'ذا', 'ذوا', 'أجمع', 'أنتن', 'صبرا', 'حزيران', 'إنما', 'مما', 'فإذا', 'بسّ', 'مه', 'مليم', 'ض', 'تفعلون', 'ءَ', 'لهم', 'ته', 'أفريل', 'كن', 'سبعين', 'كذلك', 'غداة', 'أف', 'لهن', 'صراحة', 'بات', 'ط', 'ثاء', 'هَاتِه', 'إذاً', 'ليت', 'هم', 'كأيّ', 'إلى', 'وُشْكَانَ', 'ثمة', 'كليهما', 'إنا', 'آذار', 'أخذ', 'هكذا', 'هَاتَيْنِ', 'أمامكَ', 'قطّ', 'لبيك', 'تجاه', 'مساء', 'غادر', 'علم', 'مكانكما', 'كانون', 'ن', 'كأين', 'يوليو', 'سبعمئة', 'ذلكن', 'ثماني', 'فيم', 'زعم', 'دال', 'كأن', 'أضحى', 'نحن', 'مكانَك', 'سقى', 'واو', 'بك', 'ماذا', 'هَذِي', 'اللواتي', 'عند', 'سرعان', 'هَؤلاء', 'خاء', 'هَذَيْنِ', 'أربعمئة', 'الألاء', 'اربعون', 'عشر', 'ظلّ', 'همزة', 'عشرون', 'كأنما', 'مافتئ', 'إذا', 'كلّما', 'مع', 'يوان', 'بعد', 'سحقا', 'يفعلان', 'أربعمائة', 'ذيت', 'أمد', 'فاء', 'ذانِ', 'عشرة', 'على', 'يونيو', 'ء', 'مكانكم', 'أولاء', 'له', 'لعمر', 'انقلب', 'أيّ', 'مائة', 'غدا', 'خمسون', 'بمن', 'أنتِ', 'إليكم', 'ذلكما', 'أنشأ', 'أنًّ', 'تحوّل', 'أوت', 'هَجْ', 'ذواتي', 'جعل', 'إليكَ', 'قام', 'تشرين', 'أصلا', 'استحال', 'عن', 'ليرة', 'أنى', 'خلا', 'بَسْ', 'إلّا', 'لهما', 'ث', 'جانفي', 'تَيْنِ', 'بغتة', 'عما', 'طرا', 'أم', 'سادس', 'ثاني', 'طَق', 'أمام', 'يفعلون', 'إزاء', 'تاسع', 'مايو', 'ذواتا', 'ثامن', 'جمعة', 'أربعاء', 'حمو', 'كما', 'مازال', 'ب', 'أقل', 'إياهن', 'نوفمبر', 'خمسمئة', 'تسعمئة', 'ترك', 'أيار', 'فبراير', 'ثمنمئة', 'ستمئة', 'بهم', 'اللتين', 'ق', 'ثمانين', 'خمسة', 'ذان', 'أسكن', 'رزق', 'أفٍّ', 'الذين', 'ومن', 'تخذ', 'ثلاث', 'منه', 'وإذا', 'ظ', 'ورد', 'إيه', 'آهٍ', 'بخ', 'اثنين', 'طالما', 'بيد', 'ثمّة', 'يمين', 'أن', 'إمّا', 'فيفري', 'آنفا', 'ثلاثمائة', 'شيكل', 'آه', 'و', 'أ', 'رجع', 'لها', 'بكم', 'حين', 'عين', 'كأي', 'ثلاثمئة', 'ما برح', 'إحدى', 'أُفٍّ', 'كذا', 'حار', 'ذَيْنِ', 'دولار', 'ألفى', 'هما', 'ع', 'ت', 'عليك', 'حيث', 'تِي', 'ريث', 'إيهٍ', 'كلاهما', 'إياي', 'أولالك', 'والذين', 'أنتم', 'ابتدأ', 'فمن', 'تلكما', 'طاء', 'أرى', 'ديسمبر', 'آهِ', 'زاي', 'أخبر', 'أى', 'حبيب', 'إياهم', 'الآن', 'بها', 'تفعلان', 'اثنان', 'تلكم', 'عوض', 'لدن', 'كم', 'ثلاثون', 'ما انفك', 'هلا', 'خميس', 'فيها', 'كأنّ', 'اللتان', 'أولئك', 'اللتيا', 'ّأيّان', 'خامس', 'فرادى', 'شتان', 'ز', 'كلما', 'سين', 'هلم', 'جويلية', 'عدَّ', 'كلتا', 'هن', 'ذال', 'تِه', 'حقا', 'بهن', 'قد', 'بكن', 'تبدّل', 'هنا', 'أمس', 'ضاد', 'أنّى', 'أوّهْ', 'كاد', 'بضع', 'رويدك', 'سبعة', 'إيانا', 'ثالث', 'ثمانمئة', 'عاد', 'لك', 'شبه', 'أيّان', 'صباح', 'ألا', 'حتى', 'عشرين', 'خلافا', 'د', 'فو', 'سبعون', 'أول', 'بطآن', 'أي', 'بل', 'نبَّا', 'أيا', 'ظنَّ', 'نفس', 'ا', 'إليكن', 'علق', 'بَلْهَ', 'تفعلين', 'مارس', 'رأى', 'أنتما', 'رابع', 'حيثما', 'نَّ', 'من', 'تين', 'أفعل به', 'ضحوة', 'مثل', 'كيت', 'صاد', 'لات', 'لما', 'كأيّن', 'هَاتِي', 'كليكما', 'اللائي', 'ج', 'إليكنّ', 'اتخذ', 'هاتين', 'هذان', 'شين', 'ستون', 'سمعا', 'هَذا', 'ة', 'لكما', 'هَذانِ', 'تعلَّم', 'مئتان', 'نا', 'سنتيم', 'هَذِه', 'آ', 'تحت', 'هذي', 'ستة', 'شتانَ', 'كِخ', 'تعسا', 'كسا', 'أنبأ', 'إنه', 'قرش', 'راء', 'كى', 'دينار', 'لنا', 'أيها', 'ألف', 'ذلكم', 'أحد', 'لي', 'صهٍ', 'حَذارِ', 'التي', 'حدَث', 'انبرى', 'أوه', 'فلس', 'سبعمائة', 'عامة', 'منها', 'أو', 'هيّا', 'كلَّا', 'سرا', 'بعض', 'منذ', 'ثلاثين', 'ذينك', 'مذ', 'آب', 'ثمَّ', 'هؤلاء', 'تينك', 'به', 'أنت', 'إليكما', 'تسعمائة', 'بما', 'أيضا', 'نحو', 'ش', 'عل', 'هاهنا', 'تموز', 'عاشر', 'زود', 'هذا', 'يورو', 'حمدا', 'بنا', 'أوشك', 'وجد', 'اثنا', 'صار', 'صبر', 'أكتوبر', 'أين', 'وهو', 'متى', 'ي', 'أبٌ', 'لكنَّ', 'نيسان', 'خاصة', 'ذانك', 'ها', 'هل', 'صدقا', 'ثمّ', 'هذين', 'ريال', 'عليه', 'إن', 'ثمانية', 'إذن', 'هَاتانِ', 'آض', 'حاء', 'فلان', 'أطعم', 'شرع', 'خمسين', 'عَدَسْ', 'خال', 'ما', 'ذهب', 'أمامك', 'ظاء', 'خبَّر', 'هلّا', 'أخو', 'وهب', 'مرّة', 'لا سيما', 'ذات', 'بماذا', 'صهْ', 'نَخْ', 'اربعين', 'فيما', 'كان', 'شباط', 'اللذين', 'شمال', 'نيف', 'يا', 'مادام', 'ممن', 'رُبَّ', 'ماي', 'بهما', 'ل', 'تانِ', 'آها', 'هو', 'شَتَّانَ', 'ثلاثاء', 'مكانكنّ', 'تلك', 'اثني', 'قلما', 'سبت', 'أربع', 'ذاك', 'إي', 'هي', 'ثان', 'تسع', 'سابع', 'آناء', 'الذي', 'تي', 'تسعة', 'ين', 'إليك', 'آمينَ', 'ئ', 'حيَّ', 'هَيْهات', 'حاي', 'جميع', 'م', 'ستين', 'سبتمبر', 'ذ', 'بؤسا', 'ه', 'آهاً', 'ص', 'علًّ', 'إياه', 'تسعين', 'إياهما', 'اللاتي', 'أل', 'فيه', 'اخلولق', 'حرى', 'هاء', 'وراءَك', 'ذي', 'أبو', 'ياء', 'درهم', 'هاكَ', 'تارة', 'مئة', 'أعطى', 'بعدا', 'اللذان', 'أخٌ', 'بكما', 'أهلا', 'حجا', 'هاتان', 'طفق', 'ثلاثة', 'أبدا', 'إياكن', 'دونك', 'إياها', 'تلقاء', 'ذلك', 'معاذ', 'خمس', 'أصبح', 'هللة', 'كاف', 'جيم', 'ى', 'هاك', 'وإن', 'فوق', 'آي', 'نون', 'بخٍ', 'فإن', 'حادي', 'ميم', 'إذ', 'ثمانون', 'أربعة', 'لام', 'إياك', 'خ', 'ح', 'إياكم', 'راح', 'والذي', 'ثم', 'أمّا', 'ستمائة', 'س', 'ؤ', 'ذو', 'واحد', 'قاف', 'إى', 'إياكما', 'سوى', 'ذِي', 'أكثر', 'هاته', 'ذِه', 'بين', 'أنا']

In [26]:
# Affiche quelques mots (stop-words)
print(stopwords.words('french'))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']

In [27]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in final_arabic_stopwords and word not in french_stopwords]
    return " ".join(filtered_words)

# Appliquer la suppression des stop-words
comments_df["Comments"] = comments_df["Comments"].apply(remove_stopwords)
posts_df["Contents"] = posts_df["Contents"].apply(remove_stopwords)

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

In [28]:
posts_df["Contents"]

0              جازي تمنى سنة سعيد djezzy سعيدة جديدة سنة
1      راك عطل أريد رصيد خدمة tranquilo خاص djezzy سا...
2                                   it time to be legend
3      djezzy souhaite سنة سعيدة جازي تقدم أحر تهنئة ...
4                                                   قريب
                             ...
178    إثارة لعب تتعاش خاص ooredoo تضاعف إنترنت my oo...
179          ooredoo dima رابح شيء جديد لكي ربح أستناونا
180    عاش جو رمضاني رائع خلال إفطار ftour دارتو oore...
181    ضاعف اشتراك إنترنت خاص خلال شهر رمضان my oored...
182    عاشق سينما عربي حمل تطبيق شاهد استمتع أفضل فيل...
Name: Contents, Length: 183, dtype: object

In [29]:
comments_df["Comments"]

1       سلام رحمة لدى مشكلة تعبئة بدأ نقص قليل قليل  ا...
2                                                 عام خير
3                                                 عام خير
4                                                 عام خير
5                                                 عام خير
                              ...
4556                                           رمضان كريم
4560                                           رمضان كريم
4563            غلق رقم مقر قدر استرجاع رد علي رب يجازيكم
4567    walah connexion rahi faible lyamat hadou safi ...
4569                    سلام أوريدو مشكل مرة تعبئة نزع حل
Name: Comments, Length: 3968, dtype: object

## **Sauvegarde des fichiers nettoyés**

In [30]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

# Sauvegarder les fichiers après la translittération
comments_df.to_csv("Comments_clean.csv", index=False)
posts_df.to_csv("Posts_clean.csv", index=False)

print("Prétraitement terminé et fichiers enregistrés !")

Prétraitement terminé et fichiers enregistrés !