# **Converter format ".xlsx" en ".csv" et enregistrer dans repertoire "Output"**

In [1]:
import pandas as pd
import os

# Define the paths to the input files
comments_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Comments.xlsx"
posts_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Posts.xlsx"

# Define the output directory (working directory)
output_dir = "./"

# Read the Excel files
comments_df = pd.read_excel(comments_path)
posts_df = pd.read_excel(posts_path)

# Define the output file paths
comments_csv_path = os.path.join(output_dir, "Comments.csv")
posts_csv_path = os.path.join(output_dir, "Posts.csv")

# Save the DataFrames to CSV
comments_df.to_csv(comments_csv_path, index=False)
posts_df.to_csv(posts_csv_path, index=False)

print(f"Files have been saved to {output_dir}")

Files have been saved to ./

In [2]:
# Chemin de fichier CSV
posts_csv_path = "/kaggle/working/Posts.csv"

# Lire le fichier CSV dans de DataFrame
posts_df = pd.read_csv(posts_csv_path)

# Afficher les premières lignes pour vérifier
print("\nPosts DataFrame:")
posts_df

Posts DataFrame:

,ID,Contents,Lien Post,Nb Like,Nb Love,Nb Care,Nb Wow,Nb Sad,Nb Angry,Nb Haha,Company,Date
0,1,جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...,https://www.facebook.com/djezzy/posts/78822751...,272,45,0,1,1,76,14,Djezzy,2024-01-01
1,2,راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...,https://www.facebook.com/watch/?v=106882928102...,255,28,0,1,0,12,31,Djezzy,2024-01-04
2,3,It's Time To be a legend,https://www.facebook.com/djezzy/posts/39256499...,257,51,2,0,0,2,8,Djezzy,2024-01-10
3,4,Djezzy vous souhaite Yennayer amervuh! ⴰⵙⵙⴻⴳⴰ...,https://www.facebook.com/share/p/19UDNBoQ1k/,621,231,10,3,0,1,300,Djezzy,2024-01-11
4,5,قريباً ...,https://www.facebook.com/share/v/12B9LZySBRe/,288,49,4,0,0,3,24,Djezzy,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...
178,179,إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...,https://www.facebook.com/share/p/1KGHZQuXex/,208,46,6,0,0,0,1,Ooredoo,2024-03-26
179,180,مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...,https://www.facebook.com/share/v/1Bc7FtdDPx/,625,125,14,0,1,1,1,Ooredoo,2024-03-27
180,181,عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...,https://www.facebook.com/reel/954679512980806,280,40,7,1,1,0,0,Ooredoo,2024-03-28
181,182,ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...,https://www.facebook.com/watch/?v=193245186050...,148,35,3,0,0,2,0,Ooredoo,2024-03-28
182,183,أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...,https://www.facebook.com/OoredooDZ/posts/44139...,215,46,5,0,0,1,0,Ooredoo,2024-03-30

In [3]:
import pandas as pd

# Chemin de fichier CSV
comments_csv_path = "/kaggle/working/Comments.csv"

# Lire les fichiers CSV dans des DataFrames
comments_df = pd.read_csv(comments_csv_path)

# Afficher les premières lignes pour vérifier
print("Comments DataFrame:")
comments_df

Comments DataFrame:

,ID Post,User Name,Comments
0,1,Samir Bekhouche,NaN
1,1,Yanise Yanise,سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2,1,Jj Kie,كل عام و انتم بخير
3,1,Sakou Younes,كل عام وأنتم بخير
4,1,راني نعاني,كل عام وحنا بخير
...,...,...,...
4571,183,Ĺã Rõsë Ýb,❤️❤️
4572,183,نسمات هادئة,💕💕💕💕
4573,183,ملك ملهاش غيرك,❤❤❤❤❤❤🌹
4574,183,سعيدي رضا,NaN
4575,183,جيبلي فيت فيت,❤️❤️❤️❤️

In [4]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...
1      راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...
2                               It's Time To be a legend
3      Djezzy vous souhaite Yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...
179    مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

In [5]:
comments_df["Comments"]

0                                                     NaN
1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
                              ...
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4574                                                  NaN
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4576, dtype: object

# **Pretraitement**

## **Bibiliothèques**

In [6]:
import pandas as pd
import re
import emoji
import warnings

# **Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo"**

In [7]:
# Suppression des lignes où "User Name" est "Djezzy", "Mobilis" ou "Ooredoo"
comments_df = comments_df[~comments_df["User Name"].isin(["Djezzy", "Mobilis", "Ooredoo Algérie"])]

## **Suppression des valeurs NaN "Comments"**

In [8]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

# **Supprimer les doublons consécutifs dans "Comments"**

In [9]:
comments_df = comments_df.loc[comments_df["Comments"].shift() != comments_df["Comments"]]

In [10]:
def normalize_arabic(text):
    text = text.lower()
    text = re.sub("گ", "ك", text)
    text = re.sub("ڭ", "ك", text)
    text = re.sub("ڤ", "ق", text)
    text = re.sub("ڨ", "ق", text)
    text = re.sub("پ", "ب", text)
    text = re.sub("é", "e", text)
    text = re.sub("ê", "e", text)
    text = re.sub("ë", "e", text)
    text = re.sub("ç", "c", text)
    text = re.sub("à", "a", text)
    text = re.sub("â", "a", text)
    text = re.sub("ä", "a", text)
    text = re.sub("î", "i", text)
    text = re.sub("ï", "a", text)
    text = re.sub("æ", "ae", text)
    text = re.sub("œ", "oe", text)
    return text

def replace_emojis(text):
    emojis = {
        "\U0001F601": "فرح",
        "\U0001F602": "فرح",
        "\U0001F603": "فرح",
        "\U0001F604": "فرح",
        "\U0001F605": "حزن",
        "\U0001F606": "فرح",
        "\U0001F607": "فرح",
        "\U0001F60C": "فرح",
        "\U0001F60D": "حب",
        "\U0001F60E": "حزن",
        "\U0001F611": "حب",
        "\U0001F612": "حزن",
        "\U0001F613": "حزن",
        "\U0001F615": "حزن",
        "\U0001F618": "حب",
        "\U0001F619": "حب",
        "\U0001F61A": "حب",
        "\U0001F61B": "حب",
        "\U0001F61C": "حب",
        "\U0001F61D": "حب",
        "\U0001F61E": "حب", 
        "\U0001F61F": "حب",
        "\U0001F620": "غضب",
        "\U0001F621": "غضب",
        "\U0001F622": "حزن",
        "\U0001F623": "فرح",
        "\U0001F624": "حزن",
        "\U0001F625": "حزن",
        "\U0001F626": "حزن",
        "\U0001F627": "غضب",
        "\U0001F628": "حزن",
        "\U0001F629": "حزن",
        "\U0001F62A": "حزن",
        "\U0001F62B": "حزن",
        "\U0001F62C": "حزن",
        "\U0001F62D": "حزن",
        "\U0001F62E": "حزن",
        "\U0001F62F": "حزن",
        "\U0001F630": "غضب",
        "\U0001F631": "حزن",
        "\U0001F632": "حزن",
        "\U0001F633": "حزن",
        "\U0001F635": "حزن",
        "\U0001F636": "حزن",
        "\U0001F637": "فرح",
        "\U0001F638": "فرح",
        "\U0001F639": "فرح",
        "\U0001F63A": "فرح",
        "\U0001F63B": "فرح",
        "\U0001F63C": "فرح",
        "\U0001F63D": "فرح",
        "\U0001F63E": "فرح",
        "\U0001F63F": "فرح",
        "\U0001F640": "حزن",
        "\U0001F641": "حزن",
        "\U0001F642": "فرح",
        "\U0001F643": "فرح",
        "\U0001F644": "فرح",
        "\U0001F645": "فرح",
        "\U0001F646": "فرح",
        "\U0001F647": "فرح",
        "\U0001F648": "فرح",
        "\U0001F649": "فرح",
        "\U0001F64A": "فرح",
        "\U0001F64B": "فرح",
        "\U0001F64C": "فرح",
        "\U0001F64D": "فرح",
        "\U0001F64E": "فرح",
        "\U0001F64F": "فرح",
        "\U0001FA79": "حب",
        "\U0001F970": "حب",
        "\U00002764": "حب",
        "\U0001F495": "حب",
        "\U0001F339": "حب",
    }
    for emoji, arabic_equivalent in emojis.items():
        # Ajouter un espace après chaque remplacement
        text = re.sub(emoji, " " + arabic_equivalent + " ", text)
    return text.strip()

# Appliquer la normalisation
comments_df["Comments"] = comments_df["Comments"].apply(normalize_arabic)
posts_df["Contents"] = posts_df["Contents"].apply(normalize_arabic)

comments_df["Comments"] = comments_df["Comments"].apply(replace_emojis)

In [11]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
6                                                      حب
                              ...
4570                                               🩷🩷🩷🩷🩷🩷
4571                                            حب ️ حب ️
4572                                       حب  حب  حب  حب
4573                           حب  حب  حب  حب  حب  حب  حب
4575                                  حب ️ حب ️ حب ️ حب ️
Name: Comments, Length: 4277, dtype: object

In [12]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#djezzy #happy_new...
1      راك en panne و خصك رصيد ؟\nمع خدمة tranquilo ت...
2                               it's time to be a legend
3      djezzy vous souhaite yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي ooredo...
179    مع ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

# **Nettoyage des données**

In [13]:
def clean_text(text):
    text = emoji.replace_emoji(text, replace='')  # Supprimer les emojis
    text = re.sub(r'http\S+ | htps\S+', '', str(text))  # Supprimer les hyperliens
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', str(text))  # Supprimer les URL
    text = re.sub(r'@\S+', '', str(text))  # Supprimer les mots commençant par @
    text = text.replace("_", " ").replace("#", "")  # Supprimer # et _
    text = text.replace("'", " ")  # Supprimer '
    text = re.sub(r'\. | , | ، | ؛', ' ', text)  # Remplacer certaines ponctuations
    
    # Supprimer les mots réservés
    text = re.sub(r'\bRT\b | \bRetweeted\b', '', text)
    reserved_words = r'\b(?:h{1,2}|m{1,2}|s{1,2}|Da|da|DA|Euro|جيغات|يورو|أورو|g|جيكا|جيقا|جيقي|km|kilometre|m|qr|mb|gb|حي|giga|milles|esim|Mo|mo|ko|mega|Go|جيغا|جيجا|ساعة|دج|دينار(?: جزائري)?|Dollars?|دولار)\b'
    text = re.sub(reserved_words, '', text, flags=re.IGNORECASE)

    # Supprimer tout caractère spécial sauf l'alphabet arabe et latin
    text = re.sub(r'[^a-zA-Z0-9\u0600-\u06FF\s]', '', text)
        
    # Supprimer les voyelles courtes arabes (حركات)
    harakat = "[\u064B-\u0652]"  # Comprend
    text = re.sub(harakat, '', text)

    text = re.sub(r"(.)\1{2,}", r"\1", text)  # Supprimer les caractères consécutifs en double
    text = re.sub('\d+', ' ', text)  # Supprimer les chiffres
    text = text.replace('\n', ' ').replace('/', ' ')  # Supprimer sauts de ligne et /
    text = re.sub(r'[^\w\s]', '', text)  # Supprimer les caractères spéciaux

    return text.strip()

def remove_prefixes(text):
    # Supprimer "ف" en début de phrase
    text = re.sub(r'^ف', '', text)
    # Supprimer "و" en début de phrase
    text = re.sub(r'^و', '', text)
    # Supprimer "ال" partout dans le texte
    text = re.sub(r'ال', '', text)
    return text.strip()  # Supprimer les espaces inutiles


comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

comments_df["Comments"] = comments_df["Comments"].apply(remove_prefixes)
posts_df["Contents"] = posts_df["Contents"].apply(remove_prefixes)

# Remplacer les valeurs nulles par une chaîne vide
comments_df["Comments"] = comments_df["Comments"].fillna('')
posts_df["Contents"] = posts_df["Contents"].fillna('')

comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [14]:
posts_df["Contents"]

0         جازي تتمنى لكم سنة سعيدة djezzy happy new year
1      راك en panne و خصك رصيد  مع خدمة tranquilo تاع...
2                                it  time to be a legend
3      djezzy vous souhaite yennayer amervuh     جازي...
4                                                  قريبا
                             ...
178    إثارة ألعاب تتعاش مع أحباب خاصة كي ooredoo تضا...
179    مع ooredoo ديما رابحين  وجدنا لكم حاجة جديدة ب...
180    عشنا مع بعض أجواء رمضانية رائعة من خل إفطار  f...
181    ضاعفوا اشتراك إنترنت خاص بكم خل شهر رمضان على ...
182    أنتم من عشاق سينما عربية حملوا تطبيق شاهد واست...
Name: Contents, Length: 183, dtype: object

In [15]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة  فليكسيت    و بدأت...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
6                                                      حب
                              ...
4569    سلام عليكم اوريدو عندي مشكل كل مرة نفليكسي تنح...
4571                                               حب  حب
4572                                       حب  حب  حب  حب
4573                           حب  حب  حب  حب  حب  حب  حب
4575                                       حب  حب  حب  حب
Name: Comments, Length: 4084, dtype: object

## **Correction des abréviations & Regroupement phonétique**

In [16]:
abbreviations = {
    "mrc": "merci",
    "num": "numéro",
    "numro": "numéro",
    "nn": "non",
    "bn": "bonne",
    "topp": "top",
    "شوي": "قليل",
    "شويا": "قليل",
    "لزونيتي": "الوحدات",
    "حنا": "نحن",
    "أسإلتي": "اسئلة",
    "حاص": "خاص",
    "مدام": "بينما",
    "رانا": "نحن",
    "بون": "حسن",
    "توس": "جميع",
    "سبيسيال": "منفرد",
    "سبيال": "منفرد",
    "باه": "لكي",
    "زاف": "كثيرا",
    "بزاف": "كثيرا",
    "نتمني": "نتمنى",
    "فظلكم": "فضلكم",
    "ضلم": "ظلم",
    "ردى": "رد",
    "علاش": "لماذا",
    "علاه": "لماذا",
    "علا": "لماذا",
    "هذ": "هذا",
    "تبرعو": "تبرع",
    "ابليكاسيو": "تطبيق",
    "أبليكاسيون": "تطبيق",
    "أبليكاسيو": "تطبيق",
    "الخاص بكم": "نتاعكم",
    "ديرولنا": "افعلو لنا",
    "ديرو": "افعلو",
    "نحا": "نزع",
    "دير": "افعل",
    "حاجة": "شيء",
    "نتع": "خاص ب",
    "تاع": "خاص ب",
    "تع": "خاص ب",
    "جاوبوني": "رد علي",
    "مشتاركه": "مشاركة",
    "رحو": "اذهبو",
    "هدي": "هدية",
    "هذي": "هذه",
    "يروح": "يذهب",
    "يجي": "يأتي",
    "وقتاه": "متى",
    "وقتاش": "متى",
    "وقتش": "متى",
    "تردولنا": "تردون",
    "نتاع": "خاص ب",
    "شك": "من",
    "شكون": "من",
    "نحيتوها": "نزع",
    "نحيتو": "نزع",
    "نحيت": "نزع",
    "سلفلي": "قرض",
    "سلفولي": "قرض",
    "غدوة": "غدا",
    "تلقى": "تجد",
    "نلقى": "اجد",
    "نأكتيفيها": "تفعيل",
    "نأكتيفي": "تفعيل",
    "ناكتيفي": "تفعيل",
    "نعانيو": "نعانون",
    "نعانو": "نعانون",
    "ميت حال": "رديء",
    "مفهمتش": "لم افهم",
    "انو": "انه",
    "علابالي": "اعلم",
    "ليتو": "اصبحتم",
    "وليتو": "اصبحتم",
    "تدو": "تاخذون",
    "الى": "إلى",
    "خاستني": "احتاج",
    "خستني": "احتاج",
    "مشى": "تعمل",
    "مشا": "تعمل",
    "شكا": "شكوى",
    "شكيت": "شكوى",
    "زرو": "سيء",
    "زيرو": "سيء",
    "سرفيك": "خدمة",
    "سرفيس": "خدمة",
    "جيزي اب": "djezzy app",
    "nchlh": "incha allah",
    "riglou": "regler",
    "bah": "pour",
    "nwaliw": "devenir",
    "k": "comme",
    "مراحش": "لن",
    "مهمش": "ليسو",
    "تعليع": "تعليق",
    "زااف": "كثيرا",
    "khayan": "سرق",
    "djezzyy": "djezzy",
    "ومرديتش": "لم ترد",
    "واش": "ماذا",
    "منبعد": "بعد ذلك",
    "تفتحش": "لا تفتح",
    "ندير": "افعل",
    "راه": "اصبح",
    "لازم": "يجب",
    "pix": "pixx",
    "Twanty": "Twenty",
    "orod": "prod",
    "imtiyaaz": "imtiyaz",
    "tm": "ok",
    "نم": "تم",
    "جداو": "جدا",
    "زلب": "زبل",
    "كونطرا": "عقد",
    "شري": "شراء",
    "توب": "رائع",
    "جزل": "جزيلا",
    "ياسر": "كثيرا",
    "golde": "gold",
    "mknch": "introuvable",
    "rani": "je suis",
    "شكرالكم": "شكرا لكم",
    "viv": "vive",
    "عتل": "ارسل",
    "بعت": "ارسل",
    "لاجونس": "مقر",
    "rpnd": "repond",
    "prv": "prive",
    "svp": "s il vous plais",
    "yennayer": "سنة",
    "amervuh": "سعيدة",
    "assgas": "assegas",
    "asugas": "assegas",
    "asegas": "assegas",
    "amegaz": "amegas",
    "amgaz": "amegas",
    "amegaz": "amegas",
    "amgaz": "amegas",
    "amegaz": "amegas",
    "خخ": "ضحك",
    "هه": "ضحك",
    "سبي": "سبيسيال",
    "شبكهمشكورين": "شبكه مشكورين",
    "يعطيكمصحه": "يعطيكم صحه",
    "نشله": "ان شاء الله",
    "عندوش": "لا يوجد",
    "خفظو": "تخفيض",
    "سء": "سؤال",
    "مليحة": "حسن",
    "مليحه": "حسن",
    "وله": "و الله",
    "مكمات": "مكالمات",
    "وينتا": "متى",
    "تدوها": "تاخذون",
    "felawen": "tous",
    "ya": "il y a",
    "en": "في",
    "panne": "عطل",
    "happy": "سعيدة",
    "koum": "votre",
    "ayi": "faible",
    "new": "جديدة",
    "year": "سنة",
    "years": "سنة",
    "شنو": "ما هو",
    "هدا": "هذا",
    "شالنج": "تحدي",
    "li": "qui",
    "bghi": "aime",
    "ndirlo": "faire",
    "yji": "viens",
    "lah": "pourquoi",
    "raho": "que il",
    "hbs": "arret",
    "بر": "فقط",
    "برك": "فقط",
    "غي": "الا",
    "غير": "الا",
    "الي": "الى",
    "حسنو": "اصلاح",
    "سقمو": "اصلاح",
    "جوند": "legend",
    "يجاند": "legend",
    "ليجند": "legend",
    "ارطيا": "جزء",
    "علجال": "من أجل",
    "تثقال": "بطء",
    "كون": "ليت",
    "بغى": "اراد",
    "يبغي": "يريد",
    "نبغي": "نريد",
    "تفرج": "مشاهدة",
    "ماتش": "مباراة",
    "رجا": "رجاء",
    "متمشلكش": "لا تعمل",
    "متمسيلكش": "لا تعمل",
    "لايص": "اماكن",
    "بلايص": "اماكن",
    "بلاصة": "اماكن",
    "نسقسي": "اسأل",
    "اذ": "اذا",
    "يمتي": "بلا حدود",
    "اليميتي": "بلا حدود",
    "خسني": "اريد",
    "باطل": "مجانا",
    "قولد": "gold",
    "تعيف": "بطء",
    "نسييو": "محاولة",
    "نلعبو": "لعب",
    "نكونو": "أكون",
    "عب": "لعب",
    "كف": "كيف",
    "اللهيوفقناجميعاقولويارب": "الله يوفقنا جميع اقولو يارب",
    "congratulations": "مبروك",
    "berkaw": "arret",
    "ser": "vole",
    "تردوش": "لا تردون",
    "هضرت": "تكلمت",
    "باش": "لكي",
    "تحلى": "حل",
    "تحلي": "حل",
    "لينا": "لنا",
    "حض": "حظ",
    "wech": "Quoi",
    "ndirou": "faire",
    "bach": "pour",
    "nrebhou": "gagner",
    "elfe": "mille",
    "mabrok": "felicitations",
    "koules": "tous",
    "moucharikones": "participants",
    "el": "les",
    "mabrouk": "مبروك",
    "اطوههالي": "اعطوها لي",
    "شاب": "جميل",
    "يعطيكمالصحة": "يعطيكم الصحة",
    "illa": "lent",
    "woww": "wow",
    "يارب": "يا رب",
    "كلشي": "كل شيء",
    "كنكتي": "تواصل",
    "مانكونيكتيش": "لا أتواصل",
    "يووز": "yooz",
    "يوز": "yooz",
    "وش": "ما هو",
    "وشمن": "اي",
    "ديما": "dima",
    "راه": "انه",
    "معجبتنيش": "سيء",
    "تحبسلي": "توقف",
    "انتاع": "ل",
    "لوس": "plus",
    "شكراوريدو": "شكرا أوريدو",
    "در": "فعل",
    "رهي": "انه",
    "كاين": "يوجد",
    "مباغش": "لا يريد",
    "يمدلي": "يعطيني",
    "يخرجو": "خروج",
    "اكتر": "أكثر",
    "مايمشيش": "لا يعمل",
    "سوايع": "ساعة",
    "محبتش": "لا",
    "جام": "مستحيل",
    "جامي": "مستحيل",
    "تمشلي": "تعمل",
    "ريفي": "خاص",
    "قاع": "كل",
    "منربحش": "لا أربح",
    "منربحوش": "لا أربح",
    "نقارع": "صبر",
    "مفتحتوهاليش": "لا تفتح",
    "ابونمون": "اشتراك",
    "مساج": "رسالة",
    "رجعو": "رد",
    "صحيتو": "شكرا",
    "لاتوجد": "لا توجد",
    "نلقاش": "لا أجد",
    "ما نلقاش": "لا أجد",
    "كريدي": "رصيد",
    "ريبونديولنا": "رد",
    "جد": "جدا",
    "ينحيولي": "نزع",
    "يحذفولي": "نزع",
    "ماسلفت": "لم اقترض",
    "مدايرا": "لم أفعل",
    "راهي": "إنها",
    "فور": "ممتاز",
    "هايل": "ممتاز",
    "مليح": "جيد",
    "شابة": "جميل",
    "ماصلحتليش": "لا تعمل",
    "إستلاف": "قرض",
    "خص": "اريد",
    "هاذ": "هذا",
    "شحال": "كم",
    "تاكتيفيه": "تفعيل",
    "حتان": "كي",
    "كيفاش": "كيف",
    "غلطة": "خطا",
    "ختاريت": "خيار",
    "ديالي": "خاص بي",
    "حاب": "اريد",
    "ويل": "أو",
    "ابعث": "ارسال",
    "goold": "gold",
    "ماتجاوبوش": "عدم رد",
    "مهدى": "هدية",
    "واشهرالجاي": "شهر موالي",
    "نخلصش": "لا أدفع",
    "ابليس": "plus",
    "تأكتيفها": "تفعيل",
    "هيل": "hayla",
    "هاذي": "هذه",
    "وشمن": "ما هي",
    "جزاير": "جزائر",
    "معن": "معنى",
    "فاه": "فيها",
    "فاش": "اي",
    "مكوبي": "مقطوع",
    "مي": "لكن",
    "مايمشيلك": "لا يعمل",
    "نديرلهم": "اعمل لهم",
    "تتمسخرو": "استهزاء",
    "ريبونديو": "رد",
    "plais" : "من فظلكم",
    "كفاه": "كيف",
    "ندموندي": "طلب",
    "دخلتو": "ادخال",
    "العالميه": "عالمية",
    "قات": "بقي",
    "بقات": "بقي",
    "nechlh": "incha allah",
    "jdida": "جديد",
    "كيفما": "كيف",
    "اندير": "افعل",
    "ذيم": "دائما",
    "وين": "أين",
    "راهي": "هي",
    "ماندمت": "ندم",
    "حشو": "خدعة",
    "حشوة": "خدعة",
    "انشاءاللهتكونمننصيبي": "ان شاء الله تكون من نصيبي",
    "نتمنالهم": "اتمنى",
    "راحوش": "لم يذهب",
    "بادن": "باذن",
    "الي": "الذي",
    "تغلقلو": "غلق",
    "نيمروه": "رقم",
    "يسترجعو": "استرجاع",
    "رانيني": "ranini",
    "عقوبة": "عاقبة",
    "قوب": "عاقبة",
    "حطو": "وضع",
    "لينا": "لنا",
    "ستمرار": "مستمر",
    "لابيلكاسيو": "تطبيق",
    "لبليكاسيو": "تطبيق",
    "متمشيش": "لا تعمل",
    "حبستوها": "توقف",
    "حمال": "تحميل",
    "مزان": "ميزان",
    "جيه": "جهة",
    "فلاترددو": "فلا تترددو",
    "خدمهوعروضاطاقم": "خدمة و عروض طاقم",
    "فلعاصمة": "في عاصمة",
    "nztjwice": " ",
    "refvf": " ",
    "b": " ",
    "br": " ",
    "ابار": "يبارك",
    "يحفضكم": "يحفظكم",
    "يلوس": "plus",
    "تاه": "متى",
    "بف": " ",
    "sagmou": "regler",
    "شويش": "switch",
    "بغية": "اريد",
    "dialkom": "vous",
    "sahel": "facile",
    "toop": "top",
    "هنيء": "مبروك",
    "puse": "sim",
    "pui": "puis",
    "nerbah": "gagne",
    "ghir": "sauf",
    "بيان": "جيدا",
    "ماتمشيش": "لا تعمل",
    "نحافضو": "حفاظ",
    "تخلاص": "انتهاء",
    "متعرفش": "لا تعلم",
    "خاصتا": "خاصة",
    "وفى": "و في",
    "ظل": "دائما",
    "مدرتو": "لم تفعلو",
    "لموبليس": "موبيليس",
    "را": "انه",
    "صر": "حدث",
    "rah": "il est",
    "gae": "tous",
    "dok": "maintenant",
    "لابليكاسيون": "تطبيق",
    "كلش": "كل",
    "مشاءالله": "ما شاء الله",
    "حبس": "توقف",
    "زيد": "ايضا",
    "تسرقو": "سرق",
    "تاكتيفي": "تفعيل",
    "زوعاماء": "زعماء",
    "ul": " ",
    "كدب": "كذب",
    "ميقراسيون": "تبديل",
    "شح": "كم",
    "فيهاش": "لا يوجد",
    "نجاوب": "اجيب",
    "راحت": "ذهب",
    "متسواش": "سيء",
    "تعكم": "خاص بكم",
    "حقاهايلة": "ممتاز",
    "صرقولي": "سرق",
    "صرق": "سرق",
    "ويني": "اين",
    "حمدلله": "حمد لله",
    "رحمن": "رحمان",
    "نشال": "شاء الله",
    "ماشاء": "ما شاء",
    "تنحولي": "نزع",
    "خمسلاف": "خمسة ألف",
    "خمسلاف": "خمسة ألف",
    "مفعلتهاش": "لا تفعيل",
    "سرقتولي": "سرق",
    "لكريدي": "رصيد",
    "انترنتوراها": "اين انترنت",
    "تعييف": "سيء",
    "تعيف": "سيء",
    "ضك": "الان",
    "جزى": "جزاك",
    "نشاء": "ان شاء",
    "إنشاءالله": "ان شاء الله",
    "نشالله": "ان شاء الله",
    "شاءالله": "شاء الله"
}

def replace_abbreviations(text):
    words = text.split()
    return ' '.join([abbreviations[word] if word in abbreviations else word for word in words])

comments_df['Comments'] = comments_df['Comments'].apply(replace_abbreviations)
posts_df['Contents'] = posts_df['Contents'].apply(replace_abbreviations)

In [17]:
from collections import defaultdict
import re

# Dictionnaire de regroupement phonétique
phonetic_groups = {
    "تعبئة": ["كنفليكسيو", "نفليكسي", "نفليكسيو", "فليكس", "تفليكسي", "فليكسولنا", "نفلبكسى", "فليكسيت", "كسي", "فليكسي"],
    "connexion": ["conx", "cnx", "ncx", "conexion", "connection"],
    "reseau": ["wrizo", "rizo", "riso", "rysou", "resou", "risou"],
    "اصلاح": ["ريقلوه", "ريقلو", "صلحو", "ريقولو", "صلحونا", "عدلو", "ريغلونا", "رقليو", "تريغليونا", "لوتصلحولينا", "تريقلونا", "وريقليو"],
    "شبكة": ["ريزو", "اريزو", "الريزو", "ااريزو", "خط", "خطي", "رزو"],
    "ما به": ["واشي", "وشبيه", "شبيه"],
    "لا يوجد": ["ماكاش", "مكانش", "مكاش", "مكااش", "والو", "معنديش", "الو"], 
    "أي": ["كش", "كاش"],
    "انترنت": ["كونيكسيون", "كونكسيو", "كونكزيون", "كونيكسيو", "ليدوني", "انترنات", "انترنيت","نترنت", "أنترنات", "الكنكسيو", "الانثرنات", "الانترنت", "أنترنت",  "اترنات", "الكونيكسيوو", "نت", "لكونيكسيو", "كنكسيو", "كونيكسو", "انترن"],
    "جازي": ["جايز", "جاز", "دجيزي", "دجزي", "جيزي", "جايزي"],
    "اسقاس": ["اسوكاس", "اصكاس", "اسيقاس", "اسكاس"],
    "امقاز": ["أموقاز", "امكاز"],
    "رمز": ["كود", "رزم"],
    "بارك": ["بارى", "بيار", "باراك", "يبارك"],
    "شريحة": ["لابيس", "لبيس", "بيس", "لابوس", "لبييس", "ليبيس", "بوس", "سبيسي", "لبووس", "pis"],
    "اوريدو": ["اريدوو", "لأوريد", "ياؤريدوا", "اوريدوا", "واوريدو", "ااوريدو", "اريدو"],
    "ان شاء": ["إنشاء", "نشالله", "انشاء"],
    "ilimite": ["ilm", "ilmt", "ilimiti", "ilim"],
}

# Création d’un mapping inverse (pour accélérer la recherche)
phonetic_mapping = {}
for standard, variations in phonetic_groups.items():
    for variant in variations:
        phonetic_mapping[variant] = standard

# Fonction de remplacement des variantes phonétiques
def replace_phonetic_variants(text):
    words = text.split()
    return ' '.join([phonetic_mapping[word] if word in phonetic_mapping else word for word in words])

comments_df['Comments'] = comments_df['Comments'].apply(replace_phonetic_variants)
posts_df['Contents'] = posts_df['Contents'].apply(replace_phonetic_variants)

def normalize_arabic(text):
    text = text.lower()
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "ء", text)
    text = re.sub("ئ", "ء", text)
    text = re.sub("ة", "ه", text)
    return text

# Appliquer la normalisation
comments_df["Comments"] = comments_df["Comments"].apply(normalize_arabic)
posts_df["Contents"] = posts_df["Contents"].apply(normalize_arabic)

In [18]:
posts_df["Contents"]

0        جازي تتمني لكم سنه سعيده djezzy سعيده جديده سنه
1      راك في عطل و خصك رصيد مع خدمه tranquilo خاص ب ...
2                                 it time to be a legend
3      djezzy vous souhaite سنه سعيده جازي تقدم لكم ا...
4                                                  قريبا
                             ...
178    اثاره العاب تتعاش مع احباب خاصه كي ooredoo تضا...
179    مع ooredoo dima رابحين وجدنا لكم شيء جديده لكي...
180    عشنا مع بعض اجواء رمضانيه راءعه من خل افطار ft...
181    ضاعفوا اشتراك انترنت خاص بكم خل شهر رمضان علي ...
182    انتم من عشاق سينما عربيه حملوا تطبيق شاهد واست...
Name: Contents, Length: 183, dtype: object

In [19]:
comments_df["Comments"]

1       سلام عليكم ورحمه لديا مشكله تعبءه و بدات تنقص ...
2                                      كل عام و انتم بخير
3                                       كل عام وانتم بخير
4                                        كل عام وحنا بخير
6                                                      حب
                              ...
4569    سلام عليكم اوريدو عندي مشكل كل مره تعبءه نزع خ...
4571                                                حب حب
4572                                          حب حب حب حب
4573                                 حب حب حب حب حب حب حب
4575                                          حب حب حب حب
Name: Comments, Length: 4084, dtype: object

# **Stop word**

Les Stop words ou bien les mots vides sont les mots couramment utilisés qui sont généralement ignorés par le moteur de recherche, tels que the, اللذين, إن, etc. Ces mots sont supprimés pour économiser de l’espace dans la base de données et le temps de traitement, c’est pour cette raison qu’on va essayer dans l’étape suivante d’utiliser le package ntlk pour supprimer ces mots vides.

Le package stop-words est utilisé pour supprimer les mots vides du texte en Python. Ce paquet contient des mots vides dans de nombreuses langues comme l’anglais, l’Arabe, le français, l’espagnol et plus encore.

In [20]:
# import necessary libraries
import nltk
from nltk.corpus import stopwords

# Charger les stopwords pour l'arabe et le français
nltk.download('stopwords')
arabic_stopwords = set(stopwords.words('arabic'))
french_stopwords = set(stopwords.words('french'))

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [21]:
# Affiche quelques mots (stop-words)
print(stopwords.words('arabic'))

['إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّ']

In [22]:
# Liste des mots à exclure
words_to_remove = [
    'لا', 'كثيرا', 'كثير', 'دون', 'ليس', 'ليست', 'فلا', 'غير', 'لسنا', 'لكن', 'لاسيما', 
    'لست', 'لستم', 'لم', 'لن', 'ليست', 'ليسوا', 'بئس', 'نعم', 'ساء', 'عجبا', 'عيانا', 
    'غالبا', 'فضلا', 'حسبنا', 'حسب', 'أجل', 'أما', 'إما', 'بس', 'بلى', 
    'بينما', 'حاشا', 'حبذا', 'دون', 'عدا', 'عسى', 'غير', 'فلا', 'كلا', 
    'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 
    'لعل', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لن', 'لو', 'لولا', 'لوما', 'لئن', 
    'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 
    'هيت', 'هيهات', 'وإذ', 'ولا', 'ولكن', 'ولو'
]

# Filtrer les stop words pour exclure les mots dans `words_to_remove`
final_arabic_stopwords = [word for word in arabic_stopwords if word not in words_to_remove]

# Afficher la liste finale
print(final_arabic_stopwords)

['إياهم', 'حتى', 'كل', 'مما', 'همزة', 'تفعلين', 'إذاً', 'بعد', 'كليكما', 'اتخذ', 'م', 'غادر', 'حيثما', 'خبَّر', 'ذه', 'شبه', 'هَذا', 'نون', 'سمعا', 'بهن', 'هَذَيْنِ', 'إياي', 'سبحان', 'ثمّ', 'الذين', 'خال', 'ثمانية', 'إنما', 'خاصة', 'ك', 'اللائي', 'ذانِ', 'عشر', 'مئة', 'إليك', 'مهما', 'رأى', 'إلا', 'قبل', 'ليرة', 'أيلول', 'بؤسا', 'حدَث', 'ستمئة', 'نحو', 'دواليك', 'إذا', 'أوه', 'أربعمئة', 'سبع', 'ف', 'كما', 'والذين', 'كن', 'تاسع', 'ض', 'هللة', 'جعل', 'أرى', 'أنشأ', 'نيسان', 'تحوّل', 'أفريل', 'بها', 'إنَّ', 'تفعلون', 'ماي', 'سرا', 'كليهما', 'آذار', 'خمسة', 'أيّ', 'بهم', 'اللذان', 'هلا', 'ّأيّان', 'اللتين', 'د', 'وراءَك', 'كلاهما', 'جميع', 'كذلك', 'هاتي', 'ثلاثاء', 'وإن', 'بكم', 'راح', 'ما أفعله', 'أبريل', 'هذه', 'ب', 'كاف', 'كأين', 'واحد', 'نبَّا', 'لنا', 'إنا', 'ظلّ', 'معاذ', 'اثنين', 'ذو', 'يفعلان', 'ليت', 'في', 'ثمنمئة', 'بهما', 'ذينك', 'حمو', 'شيكل', 'نيف', 'أعلم', 'ثمّة', 'آهٍ', 'حيَّ', 'أيضا', 'ثمانون', 'غ', 'ع', 'ر', 'صبر', 'مكانكنّ', 'جمعة', 'ى', 'عن', 'عشرة', 'إلى', 'واهاً', 'اللذين', 'هناك', 'بعض', 'خمس', 'هذا', 'ئ', 'أمسى', 'هيا', 'كاد', 'خلف', 'ثم', 'ؤ', 'خمسمائة', 'تحت', 'أغسطس', 'ثمان', 'اثنا', 'زعم', 'أبدا', 'نا', 'تسعة', 'مرّة', 'ترك', 'إليكنّ', 'تين', 'ذِي', 'ين', 'أنًّ', 'لكم', 'هم', 'كي', 'إليكَ', 'بسّ', 'دونك', 'طاء', 'تسعون', 'ه', 'كيف', 'أ', 'كأيّ', 'هاكَ', 'يورو', 'جويلية', 'عليك', 'سبعمائة', 'لعمر', 'كرب', 'بل', 'الذي', 'تخذ', 'ستمائة', 'بكن', 'بك', 'ثامن', 'ذاك', 'اثني', 'ط', 'منه', 'أضحى', 'خميس', 'فاء', 'سبت', 'جيم', 'حَذارِ', 'إمّا', 'فيه', 'سبعة', 'استحال', 'قام', 'هما', 'إليكم', 'ز', 'شتانَ', 'هكذا', 'سقى', 'قد', 'ذيت', 'أربعة', 'ي', 'ة', 'هاتين', 'ذلكما', 'إزاء', 'آب', 'أخو', 'عَدَسْ', 'أولالك', 'تِه', 'عشرين', 'حرى', 'والذي', 'أم', 'فوق', 'راء', 'ذَيْنِ', 'أن', 'أولاء', 'مساء', 'أُفٍّ', 'سبعون', 'ذواتا', 'مليم', 'ما', 'ستون', 'ذان', 'علًّ', 'هو', 'تاء', 'خمسين', 'هي', 'إيه', 'تجاه', 'هَاتِي', 'ثلاث', 'إلَيْكَ', 'ء', 'مكانَك', 'أنّى', 'آض', 'لبيك', 'تعسا', 'طرا', 'يونيو', 'أولئك', 'أيار', 'أنتِ', 'صهْ', 'شباط', 'آهاً', 'تسع', 'بنا', 'هَجْ', 'إيانا', 'حمدا', 'زود', 'الآن', 'مارس', 'كسا', 'بعدا', 'وإذا', 'اللتيا', 'سبعين', 'أنا', 'ألا', 'خمسمئة', 'هاتان', 'حيث', 'إياها', 'كلتا', 'فلان', 'تفعلان', 'مازال', 'ت', 'تلكم', 'أقبل', 'نحن', 'بَلْهَ', 'مذ', 'ياء', 'الألاء', 'ثمانمئة', 'أمد', 'شمال', 'عدَّ', 'أربعاء', 'أي', 'هاهنا', 'علق', 'قلما', 'إياكن', 'ثمانين', 'سحقا', 'أسكن', 'كأن', 'باء', 'جلل', 'ا', 'أمّا', 'ورد', 'ومن', 'اللتان', 'سوى', 'كلَّا', 'يناير', 'اخلولق', 'أنتم', 'آه', 'أوت', 'عند', 'شَتَّانَ', 'مئتان', 'ماذا', 'آمينَ', 'اللواتي', 'مكانكما', 'جوان', 'كان', 'هَاتَيْنِ', 'عامة', 'إذ', 'أوّهْ', 'أفعل به', 'ج', 'لام', 'اربعين', 'هذي', 'ابتدأ', 'هَذانِ', 'لدن', 'بخ', 'ستة', 'أصبح', 'أبٌ', 'ق', 'أوشك', 'ثلاثمائة', 'أصلا', 'درهم', 'أيّان', 'سين', 'فو', 'أين', 'خامس', 'تسعين', 'إلّا', 'ثاني', 'إياكما', 'أنتما', 'سابع', 'صباح', 'تِي', 'كم', 'هلم', 'هاء', 'منها', 'فإذا', 'فمن', 'حزيران', 'متى', 'بما', 'كلّما', 'كأنّ', 'انبرى', 'إنه', 'فيفري', 'أل', 'طالما', 'تموز', 'إى', 'وُشْكَانَ', 'طَق', 'ظنَّ', 'اربعون', 'أنى', 'مه', 'إيهٍ', 'تسعمئة', 'ثمَّ', 'كأنما', 'طفق', 'ديسمبر', 'يوان', 'رويدك', 'إليكن', 'عما', 'فيها', 'كانون', 'كذا', 'بطآن', 'بكما', 'غداة', 'تلك', 'تبدّل', 'عاد', 'ذات', 'أخٌ', 'إياه', 'صدقا', 'لا سيما', 'عوض', 'حين', 'ءَ', 'جير', 'لما', 'ش', 'س', 'خاء', 'دال', 'ريال', 'الألى', 'آي', 'هَؤلاء', 'سادس', 'عليه', 'طاق', 'ثاء', 'وا', 'آهِ', 'فلس', 'ثماني', 'علم', 'تشرين', 'إحدى', 'كلما', 'نفس', 'تلكما', 'يفعلون', 'شين', 'أى', 'آنفا', 'سرعان', 'فبراير', 'وجد', 'أنتن', 'تي', 'صاد', 'قاف', 'قاطبة', 'رُبَّ', 'هَيْهات', 'أخذ', 'ممن', 'هَذِه', 'تعلَّم', 'بضع', 'بماذا', 'نَّ', 'لات', 'وَيْ', 'شتان', 'لكما', 'لكنَّ', 'أفٍّ', 'هذان', 'ثالث', 'حجا', 'تارة', 'عاشر', 'حاء', 'التي', 'له', 'زاي', 'سوف', 'صراحة', 'ما انفك', 'ذِه', 'لهن', 'أعطى', 'واو', 'ذانك', 'هبّ', 'ح', 'هن', 'عل', 'بمن', 'إي', 'ذلكم', 'ذا', 'أطعم', 'بين', 'منذ', 'أنبأ', 'ما برح', 'نوفمبر', 'ثمة', 'صبرا', 'أو', 'حاي', 'ثان', 'دينار', 'من', 'أحد', 'قطّ', 'ارتدّ', 'مثل', 'كيفما', 'لك', 'لهما', 'إن', 'هاته', 'حقا', 'ث', 'جنيه', 'حادي', 'فيم', 'مادام', 'ذين', 'بات', 'تَيْنِ', 'بي', 'أينما', 'لعلَّ', 'إذن', 'هيّا', 'هلّا', 'ثلاثمئة', 'ألف', 'و', 'أبو', 'مائة', 'اثنان', 'ص', 'خلافا', 'يمين', 'أكثر', 'ثلاثة', 'وهو', 'ذلك', 'جانفي', 'أقل', 'صهٍ', 'فإن', 'تسعمائة', 'أربعمائة', 'هؤلاء', 'بَسْ', 'أهلا', 'انقلب', 'أف', 'إذما', 'به', 'بغتة', 'ستين', 'كيت', 'ثلاثين', 'خ', 'لمّا', 'تينك', 'ها', 'رزق', 'إياهن', 'اللاتي', 'أكتوبر', 'شرع', 'حمٌ', 'ذوا', 'لي', 'مافتئ', 'عشرون', 'غدا', 'وهب', 'هنا', 'درى', 'أنت', 'سبتمبر', 'لها', 'تلقاء', 'هنالك', 'يوليو', 'ته', 'بيد', 'رابع', 'قرش', 'غين', 'لهم', 'سبعمئة', 'تانِك', 'هَاتانِ', 'بخٍ', 'ن', 'أمام', 'ست', 'أول', 'حار', 'ميم', 'يا', 'ظ', 'سنتيم', 'أجمع', 'هَاتِه', 'دولار', 'كأي', 'حبيب', 'كِخ', 'وما', 'إليكما', 'أمس', 'رجع', 'أمامك', 'ذال', 'مايو', 'أيها', 'هل', 'أمامكَ', 'إياكم', 'على', 'آناء', 'صار', 'مكانكم', 'ل', 'ذ', 'آ', 'تانِ', 'ضحوة', 'ذلكن', 'هذين', 'هاك', 'فيما', 'ظاء', 'كأيّن', 'آها', 'كى', 'أخبر', 'خلا', 'هَذِي', 'ذهب', 'عين', 'إياك', 'ضاد', 'فرادى', 'ريث', 'أيا', 'إياهما', 'ثلاثون', 'ذواتي', 'أربع', 'نَخْ', 'ألفى', 'ذي', 'مع', 'خمسون']

In [23]:
# Affiche quelques mots (stop-words)
print(stopwords.words('french'))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']

In [24]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in final_arabic_stopwords and word not in french_stopwords]
    return " ".join(filtered_words)

# Appliquer la suppression des stop-words
comments_df["Comments"] = comments_df["Comments"].apply(remove_stopwords)
posts_df["Contents"] = posts_df["Contents"].apply(remove_stopwords)

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

In [25]:
posts_df["Contents"]

0            جازي تتمني سنه سعيده djezzy سعيده جديده سنه
1      راك عطل خصك رصيد خدمه tranquilo خاص djezzy ساه...
2                                 it time to be a legend
3      djezzy souhaite سنه سعيده جازي تقدم احر تهاني ...
4                                                  قريبا
                             ...
178    اثاره العاب تتعاش احباب خاصه ooredoo تضاعف انت...
179    ooredoo dima رابحين وجدنا شيء جديده لكي تربحوا...
180    عشنا اجواء رمضانيه راءعه خل افطار ftour دارتو ...
181    ضاعفوا اشتراك انترنت خاص خل شهر رمضان علي my o...
182    انتم عشاق سينما عربيه حملوا تطبيق شاهد واستمتع...
Name: Contents, Length: 183, dtype: object

In [26]:
comments_df["Comments"]

1       سلام عليكم ورحمه لديا مشكله تعبءه بدات تنقص قل...
2                                           عام انتم بخير
3                                          عام وانتم بخير
4                                           عام وحنا بخير
6                                                      حب
                              ...
4569    سلام عليكم اوريدو عندي مشكل مره تعبءه نزع خمسه...
4571                                                حب حب
4572                                          حب حب حب حب
4573                                 حب حب حب حب حب حب حب
4575                                          حب حب حب حب
Name: Comments, Length: 4084, dtype: object

## **Sauvegarde des fichiers nettoyés**

In [27]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

# Sauvegarder les fichiers après la translittération
comments_df.to_csv("Comments_clean.csv", index=False)
posts_df.to_csv("Posts_clean.csv", index=False)

print("Prétraitement terminé et fichiers enregistrés !")

Prétraitement terminé et fichiers enregistrés !